### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 with date_shift and interpolate/previous/next methods 

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#112]
It can be reproduced with "interpolate", "previous" and "next" but not "exact"
```python
import pandas as pd, atoti as tt, datetime as dt
session = tt.create_session()
store = session.read_pandas(
    pd.DataFrame({
        "date": [dt.date(2020,1,1), dt.date(2020,1,2)],
        "value": [10.0,20.0],
    }),
    store_name = "df"
)
cube = session.create_cube(store)
lvl, m, h = cube.levels, cube.measures, cube.hierarchies
m["shift"] = tt.date_shift(m["value.SUM"], on=h["date"], offset="-1D", method="interpolate")
# Do a query with dates at top level
cube.query(m["shift"]) 
```

<pre>
[...]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.quartetfs.biz.pivot.impl.Location.getCoordinate(Location.java:114)
	at com.quartetfs.biz.pivot.impl.SinglePointLocationList$SinglePointLocationListAsPointLocation.getCoordinate(SinglePointLocationList.java:210)
	at com.quartetfs.biz.pivot.impl.SinglePointLocationList.getCoordinate(SinglePointLocationList.java:97)
	at com.quartetfs.biz.pivot.impl.APointLocationListReader.getCoordinate(APointLocationListReader.java:75)
	at com.activeviam.chouket.postprocesssor.impl.DateShiftPostProcessor.getDate(DateShiftPostProcessor.java:156)
	at com.activeviam.chouket.postprocesssor.impl.DateShiftPostProcessor$DateShiftCollectionWalker.compareToTarget(DateShiftPostProcessor.java:387)
	at com.activeviam.chouket.postprocesssor.impl.DateShiftPostProcessor.walkInterpolate(DateShiftPostProcessor.java:323)
	at com.activeviam.chouket.postprocesssor.impl.DateShiftPostProcessor$DateShiftEvaluationProcedure.execute(DateShiftPostProcessor.java:232)
	at com.activeviam.copper.pivot.pp.AnalyticFunctionPostProcessor.compute(AnalyticFunctionPostProcessor.java:199)
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:164)
	... 15 more
</pre>

**Comment by fabiencelier** [comment]
This will be fixed in the next release
