### ISSUE TITLE
Parquet file load from path

### ISSUE THREAD

**Issue by AzarKhur** [atoti/atoti#121]
I am trying to load a Parquet file using the code below:

```python
import atoti as tt
import pandas as pd
import numpy as np
session = tt.create_session()
config = tt.config.create_config(max_memory="12G", )
#md = session.read_csv('BigADA_2020_04_01.csv', keys = ['Sdate'])
md = session.read_parquet('.\\part-00000-0cc10f20-920b-4f9d-808e-c3f6cba9403b-c000.snappy.parquet')
print(md.head())
```

I am getting the below error:

```
Traceback (most recent call last):

  _File "<ipython-input-5-2b2767125daa>", line 8, in <module>
    print(md.head())

  File "C:\ProgramData\Anaconda3\lib\site-packages\atoti\_docs_utils.py", line 18, in wrapper
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\atoti\store.py", line 199, in head
    return self._java_api.get_store_dataframe(self, n, self.scenario, self.keys)

  File "C:\ProgramData\Anaconda3\lib\site-packages\atoti\exceptions.py", line 75, in catch_py4j_exceptions
    ) from None

AtotiJavaException: HADOOP_HOME and hadoop.home.dir are unset.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path_
```

Could you please guide me to a solution?

**Comment by tibdex** [comment]
Hi Azar, can you give us the full Java logs located at `session.logs_path`?

Also, can you give more details about your setup:
- Did you install the lib through Pip or Conda?
- What's your atoti, Python and Java version?

Thanks.

**Comment by rcolle** [comment]
This will be fixed in the next release
