### ISSUE TITLE
Unable to process data with double quotes in between

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#135]
## Steps to reproduce

I have a pipe  delimited file with the followings:
```
subreddit|title|category|text|textcount
wallstreetbets|"DHT Holdings (DHT) |Q2 dividend is a cash bonanza"|Organization|CASH|1
wallstreetbets|"DHT Holdings (DHT) |Q2 dividend is a cash bonanza"|Organization|VLCC|1
wallstreetbets|"DHT Holdings (DHT)|Q2 dividend is a cash bonanza"|Organization|Hertz|1
wallstreetbets|Rate my "BDP" (Bear Denial Picks)|Organization|test|1
```

In the above example, I escaped the pipe in the title column by using the double quotes. 
However, the last row will cause the following error:
```
Aug 19, 2020 11:30:01 AM com.activeviam.health.monitor.impl.LoggingCsvHealthEventHandler onCsvFileParsingFailure
SEVERE: [parsing, csv, source] SEVERE 2020-08-19T03:30:01.439Z uptime=7812ms com.qfs.msg.csv.impl.PublicationQueue.notifyParserFailure:249 thread=csv-worker-CSVSource-1 thread_id=79 event_type=CsvFileParsingFailure CSV file parsing failed file=C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks\Technology\Reddit\entities.csv number_line_parsed=0
java.lang.IllegalStateException: Double-quote not closed detected. The beginning of line is wallstreetbets|Rate my "BDP
	at com.qfs.msg.csv.impl.ParserResource.stripCharBuffer(ParserResource.java:280)
```
If I set `process_quotes=False` for the datastore, the above data will cause the below exception:
```
Aug 19, 2020 2:07:17 PM com.qfs.msg.impl.LogMessageHandler onError
SEVERE: message FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks\Technology\Reddit\entities.csv, lastModifiedTime=Wed Aug 19 14:06:54 SGT 2020] failed
com.qfs.msg.csv.impl.TranslationException: The parsing of line #3 failed in source: FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks\Technology\Reddit\entities.csv, lastModifiedTime=Wed Aug 19 14:06:54 SGT 2020], text: [wallstreetbets, "DHT Holdings (DHT), Q2 dividend is a cash bonanza", Organization, Hertz]
	at com.qfs.msg.csv.impl.Parser.onTranslationFailure(Parser.java:502)
	at com.qfs.msg.csv.impl.Parser.parse(Parser.java:186)
	at com.qfs.msg.csv.impl.ParserTask.parseIteration(ParserTask.java:353)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:229)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.qfs.msg.csv.impl.ParserThread.run(ParserThread.java:64)
Caused by: com.activeviam.fwk.ActiveViamRuntimeException: Exception while translating column textcount with parser Plugin Value (key=double, class com.quartetfs.fwk.format.impl.DoubleParser) in file FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks\Technology\Reddit\entities.csv, lastModifiedTime=Wed Aug 19 14:06:54 SGT 2020]. Parsed text was "Hertz"
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:169)
	at com.qfs.msg.impl.ColumnCalculationContext.processColumn(ColumnCalculationContext.java:159)
	at com.qfs.msg.impl.ColumnCalculationContext.process(ColumnCalculationContext.java:113)
	at com.qfs.msg.impl.ColumnCalculationContext.processTuple(ColumnCalculationContext.java:82)
	at com.qfs.msg.csv.translator.impl.AColumnarTranslator.translateTuple(AColumnarTranslator.java:125)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:26)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:19)
	at com.qfs.source.impl.TupleMessageChunk.append(TupleMessageChunk.java:45)
	at com.qfs.msg.csv.impl.Parser.parse(Parser.java:181)
	... 8 more
Caused by: java.lang.NumberFormatException: Digit or '.' required
	at javolution.text.TypeFormat.parseDouble(TypeFormat.java:491)
	at javolution.text.TypeFormat.parseDouble(TypeFormat.java:562)
	at com.quartetfs.fwk.format.impl.DoubleParser.getParsedDouble(DoubleParser.java:54)
	at com.quartetfs.fwk.format.impl.DoubleParser.parse(DoubleParser.java:32)
	at com.quartetfs.fwk.format.impl.DoubleParser.parse(DoubleParser.java:22)
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:161)
	... 16 more
```

How should I escape both the quotes and delimiters within a column at the same time?

## Environment

- atoti: 0.4.3.20200731141215
- Python: 3.8.5
- Operating System: win32

**Comment by HuifangYeo** [comment]
When I encounter `java.lang.IllegalStateException: Double-quote not closed detected`, the entire csv will not be loaded. Whereas for the other exception `java.lang.NumberFormatException: Digit or '.' required`, the line is skipped and the rest of the data is loaded.

**Comment by rcolle** [comment]
You can find the role for correct escaping of double quotes in the documentation:
https://docs.atoti.io/0.4.2/lib/atoti.html?highlight=read_csv#atoti.session.Session.read_csv

Here is a copy:

process_quotes (Optional[bool]) –

Whether double quotes should be processed to follow the official CSV specification:

True:

Each field may or may not be enclosed in double quotes (however some programs, such as Microsoft Excel, do not use double quotes at all). If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.

A double quote appearing inside a field must be escaped by preceding it with another double quote.

Fields containing line breaks, double quotes, and commas should be enclosed in double-quotes.

**Comment by HuifangYeo** [comment]
Hi @rcolle,
yes, I have read that. 

As mentioned above, I set **process_quotes true**. However, our `ParserResource` class does not allow me to escape with 2 double-quotes. Hence, the below line fails:
```
wallstreetbets|Rate my "BDP" (Bear Denial Picks)|Organization|test|1
```
If I set **process_quotes false**, then how do I escape the "|" in the below column 2 - the quotes will be literally treated as quotes, so it will be interpreted as 6 tokens instead of the expected 5:
```
wallstreetbets|"DHT Holdings (DHT) |Q2 dividend is a cash bonanza"|Organization|CASH|1
```

**Comment by rcolle** [comment]
The mentioned line is not csv-compliant. 
As per the rules pasted above:

-If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.
-A double quote appearing inside a field must be escaped by preceding it with another double quote.
