### ISSUE TITLE
AtotiJavaException when create a measure simulation

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#137]
## Steps to reproduce
Simplified notebook:
```python
import atoti as tt
import pandas as pd

contract_data = [
    ['2019-06-30', 'Germany', 'Contract 1', 0.01, 'Client 1'],
    ['2019-06-30', 'Germany', 'Contract 2', 0.063, 'Client 1'],
    ['2019-06-30', 'Germany', 'Contract 3', 0.067, 'Client 2']
]
contract_df = pd.DataFrame(contract_data, columns=['Reporting Date', 'Legal Entity', 'Contract ID', 'EAD', 'Client ID'])

session = tt.create_session()

contracts_store = session.read_pandas(contract_df, keys=['Reporting Date', 'Legal Entity', 'Contract ID'], store_name='Store')

cube = session.create_cube(contracts_store, 'IFRS9', mode='no_measures')
l = cube.levels
m = cube.measures

m['EAD'] = tt.agg.sum(contracts_store['EAD'])
previous_ead = tt.shift(m['EAD'], on=l['Reporting Date'], offset=-1)

# This line cause the issue
m['EAD (DtD)'] = tt.where(previous_ead != None, m['EAD'] - previous_ead)

ead_simulation = cube.setup_simulation(
    'EAD scaling Simulation',
    levels=[l['Reporting Date'], l['Legal Entity'], l['Contract ID']],
    multiply=[m['EAD']]
)
```

## Actual Result
AtotiJavaException.
Also note that I am unable to run the **session.load_all_data()** after this issue.
Also note that this notebook was working well on atoti-plus-0.4.3.20200803144311.

## Expected Result
No exception.

## Environment
- atoti: 0.4.3.20200825191442
- Python: 3.8.5
- Operating System: win32

## Logs
**AtotiJavaException: The measure EAD does not exist in the initial cube description or has not been published yet.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path**
```
WARNING: Exception occurred in client code.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.activeviam.copper.exception.UserErrorException: The measure EAD does not exist in the initial cube description or has not been published yet.
	at com.activeviam.copper.MeasurePublisher.retrieveMeasureDescription(MeasurePublisher.java:471)
	at com.activeviam.copper.impl.DataCubeContext.retrieveMeasureDescription(DataCubeContext.java:144)
	at com.activeviam.copper.measure.NamedMeasure.computeType(NamedMeasure.java:83)
	at com.activeviam.copper.measure.NamedMeasure.getType(NamedMeasure.java:66)
	at com.activeviam.copper.measure.LeadLagMeasure.computeType(LeadLagMeasure.java:66)
	at com.activeviam.copper.measure.IInternalCopperMeasure.getType(IInternalCopperMeasure.java:59)
	at com.activeviam.chouket.pivot.measure.impl.AAtotiMeasure.doPublish(AAtotiMeasure.java:157)
	at com.activeviam.chouket.pivot.measure.impl.AAtotiMeasure.publish(AAtotiMeasure.java:134)
	at com.activeviam.chouket.pivot.measure.AtotiMeasureManager.publishCopper(AtotiMeasureManager.java:1177)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:37)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:20)
	at com.activeviam.copper.CopperDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CopperDescriptionPostProcessor.java:90)
	at com.activeviam.chouket.pivot.impl.CubeImpl$ChouketCopperActivePivotDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CubeImpl.java:1158)
	at com.activeviam.copper.CopperDescriptionPostProcessor.postProcessActivePivotDescription(CopperDescriptionPostProcessor.java:57)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchemaBuilder.postProcess(ActivePivotSchemaBuilder.java:964)
	at com.quartetfs.biz.pivot.impl.ActivePivotManagerBuilder.postProcess(ActivePivotManagerBuilder.java:267)
	at com.activeviam.chouket.pivot.impl.CubeManagerImpl.toManagerDesc(CubeManagerImpl.java:194)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:416)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:501)
	... 12 more
```

**Comment by Skyscimitar** [comment]
This issue was due to a missing dependency in the shift measure.
It will be resolved in the next release.
