### ISSUE TITLE
Hierarchy error - The Copper level matches with more than one cube level 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#139]
## Steps to reproduce
I tried to follow [tutorial](https://docs.atoti.io/0.4.2/tutorial/01-Basics.html#Multilevel-hierarchies) to regroup my attributes in the same hierarchy but I encountered the error:
```
AtotiJavaException: The Copper level Level[level=coin_symbol] matches with more than one cube level: [Level(Hierarchies, cryptocurrency, coin_symbol), Level(Hierarchies, coin_symbol, coin_symbol)]
```
thereafter the atoti cube stopped running:
```
AtotiJavaException: Pivot Twitter_Cyptocurrency is not running
```
I can re-run the command to create the cube again, thereafter, I'm able to regroup the hierarchy without error. Please see the below gif:
![hierarchy](https://user-images.githubusercontent.com/35210495/91376978-f85b9280-e850-11ea-81f2-d37096f96917.gif)

## Environment

- atoti: 0.4.2
- Python: 3.8.5
- Operating System: win32

## Logs (if relevant)

<details><pre>
Aug 27, 2020 10:30:52 AM com.activeviam.health.monitor.impl.LoggingActivePivotHealthEventHandler onActivePivotTransactionCommitted
INFO: [activepivot, transaction] INFO 2020-08-27T02:30:52.057Z uptime=11272ms com.quartetfs.biz.pivot.transaction.impl.ActivePivotSchemaTransactionManager.commit:343 thread=Thread-1 thread_id=20 event_type=ActivePivotTransactionCommittedEvent user=anonymous roles=[ROLE_USER, ROLE_ADMIN] ActivePivot transaction 2 was successfully committed on epoch 3.
Aug 27, 2020 10:30:52 AM com.quartetfs.biz.pivot.impl.ActivePivotManager doStop
INFO: [ActivePivotManager]: Stopped
Aug 27, 2020 10:30:52 AM com.qfs.multiversion.impl.EpochManager$DiscardOnGcTask run
INFO: Thread com.qfs.multiversion.impl.EpochManager$DiscardOnGcTask@7af39feb is interrupted!
Aug 27, 2020 10:30:52 AM py4j.reflection.MethodInvoker invoke
WARNING: Exception occurred in client code.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.activeviam.copper.exception.UserErrorException: The Copper level Level[level=coin_symbol] matches with more than one cube level: [Level(Hierarchies, cryptocurrency, coin_symbol), Level(Hierarchies, coin_symbol, coin_symbol)]
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.findLevelInformation(CubeHelper.java:364)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.lambda$getLevelInformation$0(CubeHelper.java:271)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.computeIfAbsent(CubeHelper.java:308)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.getLevelInformation(CubeHelper.java:271)
	at com.activeviam.copper.CubeHelper.getLevelInformation(CubeHelper.java:131)
	at com.activeviam.copper.CubeHelper.getLevelIdentifier(CubeHelper.java:109)
	at com.activeviam.copper.store.Mapping.createMappingForProcedure(Mapping.java:89)
	at com.activeviam.copper.JoinPublisher.createKey(JoinPublisher.java:448)
	at com.activeviam.copper.JoinPublisher.publish(JoinPublisher.java:212)
	at com.activeviam.copper.HierarchyPublisher.publish(HierarchyPublisher.java:139)
	at com.activeviam.copper.impl.DataCubeContext.publish(DataCubeContext.java:182)
	at com.activeviam.copper.hierarchy.BaseCopperSingleLevelAnalysisHierarchy.publish(BaseCopperSingleLevelAnalysisHierarchy.java:148)
	at com.activeviam.copper.hierarchy.BaseCopperSingleLevelAnalysisHierarchy.publish(BaseCopperSingleLevelAnalysisHierarchy.java:37)
	at com.activeviam.chouket.pivot.impl.SingleLevelCopperHierarchy.doPublish(SingleLevelCopperHierarchy.java:149)
	at com.activeviam.chouket.pivot.alambyk.impl.ACopperDefinition.publish(ACopperDefinition.java:67)
	at com.activeviam.chouket.pivot.impl.HierarchiesManager.lambda$publishCopper$7(HierarchiesManager.java:243)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.activeviam.chouket.pivot.impl.HierarchiesManager.publishCopper(HierarchiesManager.java:243)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:36)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:20)
	at com.activeviam.copper.CopperDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CopperDescriptionPostProcessor.java:90)
	at com.activeviam.chouket.pivot.impl.CubeImpl$ChouketCopperActivePivotDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CubeImpl.java:1242)
	at com.activeviam.copper.CopperDescriptionPostProcessor.postProcessActivePivotDescription(CopperDescriptionPostProcessor.java:57)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchemaBuilder.postProcess(ActivePivotSchemaBuilder.java:964)
	at com.quartetfs.biz.pivot.impl.ActivePivotManagerBuilder.postProcess(ActivePivotManagerBuilder.java:267)
	at com.activeviam.chouket.pivot.impl.CubeManagerImpl.toManagerDesc(CubeManagerImpl.java:194)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:416)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:505)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refreshPivot(SimpleActiveViamSession.java:537)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.refreshPivot(ActiveViamSessionApiImpl.java:133)
	... 12 more

Aug 27, 2020 10:34:34 AM py4j.reflection.MethodInvoker invoke
WARNING: Exception occurred in client code.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: Pivot Twitter_Cyptocurrency is not running
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.retrieveHierarchies(ActiveViamSessionApiImpl.java:505)
	... 12 more

</pre></details>

**Comment by rcolle** [comment]
Thanks for reporting.

I can understand the initial error, since a copper join relies on existing levels to match the mapping keys, and in this case there are 2 levels that match the same key (coin_symbol). We need to see what can be done for this.

I'm more surprised that it seems to work the second time. It's also worth looking at.

I'm assigning this to @a-manai for further investigation.

As as side note, after regrouping the levels under the same hierarchy, do you expect / want the single level `coin_symbol` hierarchy to still exist?

**Comment by rcolle** [comment]
By the way, you can slightly re-arrange your code to avoid this issue:

```
# In[1]:


import atoti as tt
import pandas as pd
from atoti.config import create_config


# In[2]:


config = create_config(metadata_db="./metadata.db", sampling_mode=tt.sampling.FULL)
session = tt.create_session(config=config)


# In[3]:


cyptocurrency_price_store = session.read_csv(
    "crypto_prices.csv", keys=["date", "coin_symbol"], store_name="cyptocurrency price"
)


# In[4]:


tweet_store = session.read_csv(
    "currency_tweets.csv",
    keys=["tweet_id", "coin_symbol", "date"],
    store_name="tweet_currency",
)
tweet_sentiment = session.read_csv(
    "tweets_sentiments.csv", keys=["tweet_id"], store_name="tweet_sentiment"
)


# In[5]:


cube = session.create_cube(cyptocurrency_price_store, "Twitter_Cyptocurrency")


# In[6]:


cube.schema


# In[7]:


m = cube.measures
l = cube.levels
h = cube.hierarchies


# In[8]:


cube


# In[9]:


del h["coin_symbol"]
del h["currency_name"]
h["cryptocurrency"] = [cyptocurrency_price_store["coin_symbol"], cyptocurrency_price_store["currency_name"]] 


# In[10]:


del l["date"]
del l["time"]
h["timeline"] = [cyptocurrency_price_store["date"], cyptocurrency_price_store["time"]] 


# In[11]:

# Move the join after re-arranging the hierarchies.
cyptocurrency_price_store.join(tweet_store)
tweet_store.join(tweet_sentiment)


# In[12]:


cube.schema


# In[13]:


cube



```

**Comment by HuifangYeo** [comment]
I realize that creating the cube second time, I lose the joins. Hence the levels can be created.
Even if I tried to create the joins, they do not appear in the schema.

As for the side note, in the case of the currency, it would be nice to keep the second level hierarchy (currency_name). It's fine to delete the single level coin_symbol hierarchy as it can be collapsed in pivot table (no impact visually).

**Comment by HuifangYeo** [comment]
Hi @rcolle,

your propose solution does creates the hierarchy but the resulting join is incorrect and measures value becomes a little unpredictable.

I have data at the hour 2:
![image](https://user-images.githubusercontent.com/35210495/91530344-8319bb80-e93d-11ea-99fc-6fabeab8329b.png)

Price which is derived from `value.VALUE` has a value but `value.VALUE` itself has none.
![image](https://user-images.githubusercontent.com/35210495/91530509-cd02a180-e93d-11ea-8a2f-84c31608efde.png)

I created the join as follows
```
date_store.join(cyptocurrency_price_store, mapping={"coin_symbol":"coin_symbol", "date":"date", "hour":"hour"})
```
So I should be able to filter the date. However, it is pulling out all the dates when I tried to filter to 2020-08-21:
![image](https://user-images.githubusercontent.com/35210495/91530952-8c575800-e93e-11ea-85b5-e57cdccccfad.png)

Please see the attached notebook in case I have implemented something differently:
[del_hierarchy.zip](https://github.com/atoti/atoti/files/5140547/del_hierarchy.zip)

**Comment by HuifangYeo** [comment]
I'm baffled. If I do not create the multi-level hierarchy, the filtering mentioned in the [previous comment](https://github.com/atoti/atoti/issues/139#issuecomment-682363589) is fine.

However, where I have 2 records under the hour 2, the `value.VALUE` which is automatically created during cube creation is still not showing any value:
![image](https://user-images.githubusercontent.com/35210495/91534666-7cdb0d80-e944-11ea-9914-010b8577bb77.png)

**Comment by HuifangYeo** [comment]
> I'm baffled. If I do not create the multi-level hierarchy, the filtering mentioned in the [previous comment](https://github.com/atoti/atoti/issues/139#issuecomment-682363589) is fine.
> 
> However, where I have 2 records under the hour 2, the `value.VALUE` which is automatically created during cube creation is still not showing any value:
> ![image](https://user-images.githubusercontent.com/35210495/91534666-7cdb0d80-e944-11ea-9914-010b8577bb77.png)

This is answered by https://github.com/atoti/atoti/issues/143#issuecomment-682395750

**Comment by rcolle** [comment]
So ... you've hit quite a few hair raising points :-)

First of all, you've found yourself in single-value "hell".

The first observation has been answered in #143, explaining why there are no values above certain levels for single values.

The second observation (why is there a `price` value then?) comes from the fact that we "help" people when creating aggregations on top of a single value.
When you write `m["price"] = tt.agg.mean(m["value.VALUE"], scope=tt.scope.origin(l["hour"]))`, we actually add `date` and `coin_symbol` to the scope to make sure that `value.VALUE` is always defined.

Both these points are debatable, and we're planning to work on the automated `VALUE` aggregation to avoid all these confusions. See https://github.com/activeviam/atoti/issues/1430. 


Finally, the last point (filter on date not working) is caused by a core bug:
https://github.com/activeviam/activepivot/blob/37d3dbe264f5cd92b28472ec5d1c35863e88272a/pivot/core/impl/src/main/java/com/quartetfs/biz/pivot/cube/hierarchy/axis/impl/LocationBuilder.java#L123
I'll file a core ticket for it.

**Comment by rcolle** [comment]
@a-manai , regardless of all the raised points, the initial issue still exists:
```
AtotiJavaException: The Copper level Level[level=coin_symbol] matches with more than one cube level: [Level(Hierarchies, cryptocurrency, coin_symbol), Level(Hierarchies, coin_symbol, coin_symbol)]
```

**Comment by bloussou** [comment]
@HuifangYeo can you still reproduce the issue ? If not can you close this issue ?

I don't manage to reproduce in `0.7.0` with:
```python
import atoti as tt
session = tt.Session()
cryptocurrency_table = session.create_table(
    "cryptocurrency price",
    types={
        "date": tt.LOCAL_DATE,
        "coin_symbol": tt.STRING,
        "datetime": tt.STRING,
        "currency_name": tt.STRING,
    },
    keys=["date", "coin_symbol"]
)
tweet_currency = session.create_table(
    "tweet_currency",
    types={
        "tweet_id": tt.LONG,
        "coin_symbol": tt.STRING,
        "date": tt.LOCAL_DATE,
        "created_at": tt.STRING,
    },
    keys=["date", "coin_symbol", "tweet_id"]
)
tweet_sentiment = session.create_table(
    "tweet_sentiment",
    types={
        "tweet_id": tt.LONG,
        "retweet_count": tt.INT,
    },
    keys=["tweet_id"]
)
cryptocurrency_table.join(tweet_currency)
tweet_currency.join(tweet_sentiment)
cube = session.create_cube(cryptocurrency_table)
h, l, m = cube.hierarchies, cube.levels, cube.measures

h["cryptocurrency"] = [l["coin_symbol"], l["currency_name"]]
```
