### ISSUE TITLE
 atoti.array.quantile - Server error: NullPointerException

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#152]
Quantile function gives a null pointer exception for some reason.

```python
import atoti
from atoti.config import create_config
session = atoti.create_session()

pls = [i for i in range(250)]



import pandas as pd
df = pd.DataFrame(data = {"observation": "A", "values": pls})
observations = session.read_pandas(
    df,
    "Observations"
)
cube = session.create_cube(observations, "Observations")
m = cube.measures

m['Vector'] = pls

m["Percentile Lower center"] = atoti.array.quantile(
    m["Vector"],
    (1 - 0.975),
    interpolation="lower",
    mode="center",
)
m["Percentile Midpoint center"] = atoti.array.quantile(
    m["Vector"],
    (1 - 0.975),
    interpolation="midpoint",
    mode="center",
)

cube.query(m["Percentile Lower center"], m["Percentile Midpoint center"])
```

## Actual Result

In the UI - Nullpointer

In the cube.query:

```
RuntimeError: ('Request failed', {'status': 'error', 'error': {'errorChain': [{'type': 'NullPointerException'}, {'type': 'PostProcessorEvaluationException', 'message': 'An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember'}, {'type': 'RuntimeException', 'message': 'com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember'}, {'type': 'RuntimeException', 'message': 'java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember'}, {'type': 'QueryException', 'message': 'Could not execute query at epoch 1. : ActivePivotSyncActionQuery: action=MdxAction (mdx=SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@5a317912'}, {'type': 'MdxException', 'message': 'Error with the following query: SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]'}, {'type': 'BadArgumentException', 'message': '[400] com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]'}], 'stackTrace': 'com.qfs.fwk.services.BadArgumentException: [400] com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]
	at com.qfs.pivot.rest.query.impl.JsonQueryService.executeQuery(JsonQueryService.java:215)
	at com.qfs.pivot.rest.query.impl.JsonQueryService.executeMdxQuery(JsonQueryService.java:108)
	at com.qfs.pivot.rest.query.impl.QueriesRestService.mdxQuery(QueriesRestService.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:166)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.qfs.pivot.servlet.impl.ContextValueFilter.doFilter(ContextValueFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:426)
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:408)
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.execute(ASelectStatementExecutor.java:397)
	at com.qfs.pivot.rest.query.impl.JsonQueryService$JsonSelectExecutor.execute(JsonQueryService.java:316)
	at com.qfs.pivot.rest.query.impl.JsonQueryService$JsonSelectExecutor.execute(JsonQueryService.java:294)
	at com.qfs.pivot.rest.query.impl.JsonQueryService.executeQuery(JsonQueryService.java:210)
	... 65 more
Caused by: com.quartetfs.fwk.query.QueryException: Could not execute query at epoch 1. : ActivePivotSyncActionQuery: action=MdxAction (mdx=SELECT {[Measures].[Percentile Lower center],[Measures].[Percentile Midpoint center]} ON COLUMNS FROM [Observations]), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@5a317912
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.getWithQueriesTimeLimit(ActivePivotVersion.java:1523)
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion.execute(ActivePivotVersion.java:936)
	at com.quartetfs.biz.pivot.query.impl.ActivePivotSyncUtils.activePivotSyncExec(ActivePivotSyncUtils.java:94)
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:424)
	... 70 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1064)
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.getWithQueriesTimeLimit(ActivePivotVersion.java:1494)
	... 73 more
Caused by: java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember
	at java.base/java.util.concurrent.ForkJoinTask.completeExceptionally(ForkJoinTask.java:953)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.performExceptionalCompletion(CancellableCountedCompleter.java:291)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:278)
	at java.base/java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:592)
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.afterCompute(ActivePivotVersion.java:1377)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:157)
	at com.quartetfs.biz.pivot.context.impl.ContextualCancellableCountedCompleter.afterExec(ContextualCancellableCountedCompleter.java:124)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:181)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure Percentile Lower center on location AllMember|AllMember
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:178)
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.onRegularCompletion(PostProcessedAggregatesRetrieval.java:303)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:263)
	at com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.tryCompleteParents(MultiCancellableCountedCompleter.java:244)
	at com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.onRegularCompletion(MultiCancellableCountedCompleter.java:336)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:263)
	at java.base/java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:592)
	at com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$SingleParentCompleter.afterCompute(MultiCancellableCountedCompleter.java:557)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:157)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.activeviam.chouket.pivot.alambyk.impl.VectorQuantileOperation.lambda$getCopperDefinitionFunction$342919d0$1(VectorQuantileOperation.java:99)
	at com.activeviam.copper.operation.operator.Operators$ObjectRecordMapFunction.evaluate(Operators.java:707)
	at com.activeviam.copper.operation.function.TypeConvertedCopperFunction.evaluate(TypeConvertedCopperFunction.java:61)
	at com.activeviam.copper.pivot.pp.MapperPostProcessor.evaluate(MapperPostProcessor.java:77)
	at com.quartetfs.biz.pivot.postprocessing.impl.ABasicPostProcessor$TransformationProcedure.doTransform(ABasicPostProcessor.java:290)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult$AObjectTransformationProcedure.transform(PointListRetrievalResult.java:2706)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult$3.doExecute(PointListRetrievalResult.java:1192)
	at com.quartetfs.biz.pivot.cellset.impl.AInterruptibleValuesProcedure.execute(AInterruptibleValuesProcedure.java:46)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.forEachPoint(PointListRetrievalResult.java:978)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.transformInto(PointListRetrievalResult.java:1175)
	at com.quartetfs.biz.pivot.cellset.impl.PostProcessedRetrievalResultWriter.transformAndContribute(PostProcessedRetrievalResultWriter.java:227)
	at com.quartetfs.biz.pivot.query.aggregates.impl.AdvancedAggregatesRetriever.transformAndContribute(AdvancedAggregatesRetriever.java:185)
	at com.quartetfs.biz.pivot.postprocessing.impl.ABasicPostProcessor.compute(ABasicPostProcessor.java:199)
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:164)
	... 15 more
'}})
```

## Expected Result

```python
import numpy as np
print(np.quantile(pls, 0.025, interpolation = "linear"))
print(np.quantile(pls, 0.025, interpolation = "lower"))
```

```
6.2250000000000005
6
```

## Environment

Welcome to atoti 0.4.3.20200729154535!

**Comment by Skyscimitar** [comment]
Hi @APolyakova , There is actually an error in the examples of the documentation. The argument value for `mode` sholud be `centered` not `center`. I've changed the docs and added checks for the values in the python API so the error message is understandable in case of future mistakes in the docs.

**Comment by APolyakova** [comment]
Thank you @Skyscimitar
