### ISSUE TITLE
JupyterLab Build failed on installation stage

### ISSUE THREAD

**Issue by zkid18** [atoti/atoti#154]
Facing the problem of installation the JupyterLab with the atoti extension. 
I following the docs from the [official](https://docs.atoti.io/0.4.3/install_conda.html) website. 

## Steps to reproduce

Double-check that atoti and its companion packages have been successfully installed

```
> sudo conda install atoti jupyterlab jupyterlab-atoti nodejs openjdk python

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
And then run the jupyter lab build

`jupyter lab build --dev-build False --minimize True`

## Actual Result

```
[LabBuildApp] JupyterLab 2.2.8
[LabBuildApp] Building in /opt/tljh/user/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
```

## Environment

```
Ubuntu 18.04 x86_64
conda 4.8.5
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.5
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```
Using the Google Cloud VM if that matters

You may run the following Python code:

## Logs (if relevant)
The `log file`

```
[LabBuildApp] Building in /opt/tljh/user/share/jupyter/lab
[LabBuildApp] Node v14.11.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 642, in build
    clean=clean_staging

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/site-packages/jupyterlab/commands.py", line 1095, in _populate_staging
    shutil.copy(pjoin(HERE, 'staging', fname), target)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

[LabBuildApp]   File "/opt/tljh/user/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:

[LabBuildApp] PermissionError: [Errno 13] Permission denied: '/opt/tljh/user/share/jupyter/lab/staging/index.js'
```

**Comment by rcolle** [comment]
Hi,

Thanks for reporting this. 

You installed the conda packages as a sudoer but tried to build jupyterlab without privileges. This likely explain the `PermissionError`. 
Can you try to run it with sudo privileges?
`jupyter lab build --dev-build False --minimize True`

Out of curiosity, why did you need to use `sudo` to install the conda packages?

**Comment by fabiencelier** [comment]
The [miniconda troubleshooting guide](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#permission-denied-errors-after-using-sudo-conda-command) recommends to not use `sudo` with conda:

> Once you run conda with sudo, you must use sudo forever. We recommend that you NEVER run conda with sudo.

**Comment by zkid18** [comment]
Sure, I tried to launch with `sudo` as well

**Comment by tibdex** [comment]
> Sure, I tried to launch with sudo as well

Can you try to install the Conda packages and rebuild JupyterLab without ever using `sudo`?

**Comment by tibdex** [comment]
Since atoti 0.5.0, our JupyterLab extension is [prebuilt](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-extensions) so this issue isn't relevant anymore.
