### ISSUE TITLE
Aggregate Provider bug

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#155]
## Steps to reproduce
Here is a notebook reproducing the bug

I am sorry if it is still a little complicated but I didn't succeed to minimize more the code.

````
import atoti as tt
import pandas as pd
from atoti._providers import bitmap, leaf

size = 4
df = pd.DataFrame({"l1" : [i % 4 for i in range(size)],
                  "l2": [ "l2_" + str(i) for i in range(size)],
                  "m1": [i for i in range(size)],
                   "m2": [i for i in range(size)],
                   "m3":[i for i in range(size)],
                   "m4":[i for i in range(size)]
                  })

session = tt.create_session()
store = session.read_pandas(df, store_name="main")
cube = session.create_cube(store, mode='no_measures')
l = cube.levels
m = cube.measures

m["m1"] = tt.agg.sum(store["m1"])

m["test1"] = tt.agg.mean(store["m3"])
m["test2"] = tt.shift(m['test1'], on=l['l1'], offset=-1)
# if measure 'bugger' is commented there is no bug
m['bugger'] = tt.where(m['test2'] != None, m['test1'] - m['test2'])

cube._aggregate_providers = [
    bitmap(
        levels=[
            lvl for lvl in cube.levels.values()
        ], 
        measures=[m["m1"]]
    )
]

test3 = tt.filter(tt.agg.sum_product(store['m1'], store['m2'], store["m3"]), l["l1"] == 1)
test4 = tt.filter(tt.agg.sum_product(store['m1'], store['m2'], store['m4']), l["l1"] == 2)

m["m3"] = test3 + test4

# You can put the aggregate provide at the end and the error will be thrown by the creation of the aggregate provider.
````

## Actual Result

````
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<ipython-input-10-d026a9c3752b> in <module>
      2 test4 = tt.filter(tt.agg.sum_product(store['m1'], store['m2'], store['m4']), l["l1"] == 2)
      3 
----> 4 m["m3"] = test3 + test4

~\.conda\envs\atoti0.4.3\lib\site-packages\atoti\measures.py in __setitem__(self, key, value)
     89             raise ValueError(f"Cannot create a measure from {value}") from err
     90 
---> 91         self._java_api.refresh_pivot()
     92 
     93     def __delitem__(self, key: str):

~\.conda\envs\atoti0.4.3\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     68                     Get the logs path with : session.logs_path
     69                     """
---> 70             raise AtotiJavaException(
     71                 cause, str(java_exception), java_exception,
     72             ) from None

AtotiJavaException: State transition INIT => STARTED failed because of an internal exception.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path
````

## Environment

- atoti: 0.4.3.20200901110322
- Python: 3.8.5
- Operating System: win32

## Logs (if relevant)

<pre>
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.quartetfs.fwk.AgentException: State transition INIT => STARTED failed because of an internal exception.
	at com.activeviam.chouket.impl.SimpleActiveViamSession.doRefreshPivot(SimpleActiveViamSession.java:533)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refreshPivot(SimpleActiveViamSession.java:491)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.refreshPivot(ActiveViamSessionApiImpl.java:118)
	... 12 more
Caused by: com.quartetfs.fwk.AgentException: State transition INIT => STARTED failed because of an internal exception.
	at com.quartetfs.fwk.impl.AgentState.transitionState(AgentState.java:163)
	at com.quartetfs.fwk.impl.AAtomicAgent.transitionState(AAtomicAgent.java:226)
	at com.quartetfs.fwk.impl.AAtomicAgent.start(AAtomicAgent.java:115)
	at com.quartetfs.biz.pivot.impl.DelegateActivePivotManager.setAndStartUnderlying(DelegateActivePivotManager.java:50)
	at com.activeviam.chouket.pivot.impl.CubeManagerImpl.refresh(CubeManagerImpl.java:269)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.doRefreshPivot(SimpleActiveViamSession.java:517)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at com.qfs.store.transaction.impl.TransactionManager.performMaintenanceOperation(TransactionManager.java:291)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.catchUpMultiBranch(AsyncContinuousCompositeSelection.java:818)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.doAddListenerOnCurrentSelection(AsyncContinuousCompositeSelection.java:628)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.addListener(AsyncContinuousCompositeSelection.java:556)
	at com.qfs.store.selection.IContinuousCompositeSelection.addListener(IContinuousCompositeSelection.java:352)
	at com.activeviam.copper.recast.MutableUpdatableDatastoreSelectionSessionHolder.registerInitialSelection(MutableUpdatableDatastoreSelectionSessionHolder.java:157)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchema.afterStart(ActivePivotSchema.java:254)
	at com.quartetfs.fwk.impl.AAtomicAgent.start(AAtomicAgent.java:124)
	at com.quartetfs.biz.pivot.impl.ActivePivotManager.doStart(ActivePivotManager.java:182)
	at com.quartetfs.fwk.impl.AAtomicAgent$4.run(AAtomicAgent.java:119)
	at com.quartetfs.fwk.impl.AgentState.transitionState(AgentState.java:159)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at com.qfs.store.impl.ChunkArray.getColumn(ChunkArray.java:90)
	at com.qfs.pivot.agg.impl.AggregateStore.bindSource(AggregateStore.java:1285)
	at com.qfs.pivot.cube.provider.bitmap.impl.AIndexedAggregateCollector.contribute(AIndexedAggregateCollector.java:153)
	at com.qfs.pivot.cube.provider.partition.impl.APartitionedAggregateCollector$ContributionTask.computeSafely(APartitionedAggregateCollector.java:178)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.execSafely(CancellableCountedCompleter.java:141)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:171)
	at com.qfs.pivot.cube.provider.bitmap.impl.AIndexedAggregateProviderTransaction$TransactionOperationExecutor.process(AIndexedAggregateProviderTransaction.java:608)
	at com.qfs.pivot.cube.provider.bitmap.impl.AIndexedAggregateProviderTransaction$TransactionOperationExecutor.process(AIndexedAggregateProviderTransaction.java:570)
	at com.qfs.util.impl.AAsyncConsumer.process(AAsyncConsumer.java:126)
	at com.qfs.pivot.cube.provider.bitmap.impl.AIndexedAggregateProviderTransaction$TransactionOperationExecutor.process(AIndexedAggregateProviderTransaction.java:603)
	at com.qfs.util.impl.AAsyncConsumer$ConsumerProcedure.consume(AAsyncConsumer.java:156)
	at com.qfs.concurrent.impl.SingleConsumerQueue.tryConsume(SingleConsumerQueue.java:293)
	at com.qfs.util.impl.AAsyncConsumer$ConsumeTask.compute(AAsyncConsumer.java:185)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
</pre>

**Comment by fabiencelier** [comment]
This was a bug In ActivePivot when you have a sum_product based on a field X and put another measure based on X into an aggregate provider.

It has been fixed and the fix has been included in atoti, it will be available in the next release.
