### ISSUE TITLE
measure creation with scope sibling throws exception

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#156]
## Steps to reproduce

Please see attached [sibling.zip](https://github.com/atoti/atoti/files/5264934/sibling.zip).

Below are my hierarchies:
![image](https://user-images.githubusercontent.com/35210495/93952925-a1c47400-fd7c-11ea-86e3-da1601a5665c.png)

Using scope `origin` is fine on the below but not sibling.

```
m["min"] = tt.agg.min(m["returns.MEAN"], scope=tt.scope.siblings(cube.levels[("Hierarchies", "time_series", "date")]))
```

## Actual Result
```
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<ipython-input-20-ad3fdede7e90> in <module>
----> 1 m["min"] = tt.agg.min(m["returns.MEAN"], scope=tt.scope.siblings(cube.levels[("Hierarchies", "time_series", "date")]))

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\measures.py in __setitem__(self, key, value)
     89             raise ValueError(f"Cannot create a measure from {value}") from err
     90 
---> 91         self._java_api.refresh_pivot()
     92 
     93     def __delitem__(self, key: str):

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     68                     Get the logs path with : session.logs_path
     69                     """
---> 70             raise AtotiJavaException(
     71                 cause, str(java_exception), java_exception,
     72             ) from None

AtotiJavaException: None
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path
```

## Environment
- atoti: 0.4.3
- Python: 3.8.5
- Operating System: win32

## Logs (if relevant)

```
Sep 23, 2020 9:05:03 AM py4j.reflection.MethodInvoker invoke
WARNING: Exception occurred in client code.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.activeviam.chouket.pivot.measure.impl.AtotiSiblingsAggregationMeasure.getCopperMeasure(AtotiSiblingsAggregationMeasure.java:60)
	at com.activeviam.chouket.pivot.measure.impl.AAtotiMeasure.doPublish(AAtotiMeasure.java:157)
	at com.activeviam.chouket.pivot.measure.impl.AAtotiMeasure.publish(AAtotiMeasure.java:139)
	at com.activeviam.chouket.pivot.measure.AtotiMeasureManager.publishCopper(AtotiMeasureManager.java:1173)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:37)
	at com.activeviam.chouket.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:20)
	at com.activeviam.copper.CopperDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CopperDescriptionPostProcessor.java:90)
	at com.activeviam.chouket.pivot.impl.CubeImpl$ChouketCopperActivePivotDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CubeImpl.java:1158)
	at com.activeviam.copper.CopperDescriptionPostProcessor.postProcessActivePivotDescription(CopperDescriptionPostProcessor.java:57)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchemaBuilder.postProcess(ActivePivotSchemaBuilder.java:964)
	at com.quartetfs.biz.pivot.impl.ActivePivotManagerBuilder.postProcess(ActivePivotManagerBuilder.java:267)
	at com.activeviam.chouket.pivot.impl.CubeManagerImpl.toManagerDesc(CubeManagerImpl.java:194)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.doRefreshPivot(SimpleActiveViamSession.java:556)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refreshPivot(SimpleActiveViamSession.java:540)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.refreshPivot(ActiveViamSessionApiImpl.java:127)
	... 12 more
```

**Comment by HuifangYeo** [comment]
Sorry, my bad. `atoti.scope.siblings` expects hierarchy and not levels as parameter.
The below works:
```
m["min"] = tt.agg.min(m["returns.MEAN"], scope=tt.scope.siblings(h["time_series"]))
```

**Comment by rcolle** [comment]
Thanks @HuifangYeo .
I'm reopening it and assigning to @a-manai so that we can validate the type of inputs in the `scope` methods to avoid the unreadable java stack trace.

**Comment by Skyscimitar** [comment]
Typeguard handles the incorrect input type with a clear error message now.
