### ISSUE TITLE
Cannot read 'int' value from an instance of ArrayChunkLongNullable when using floor in atoti.array.n_lowest

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#159]
## Steps to reproduce

Error when using `floor` for the argument of `n_lowest`, `nth_lowest`, `n_lowest_indices`, `n_greatest`, `nth_greatest` and `n_greatest_indices`

```python
m["array"] = [ 10.0, 20.0, 30.0, 40.0, 50.0, 60.0 ]
m["3.5"] = 3.5
m["3"] = tt.math.floor(m["3.5"])
m["3 lowest"] = tt.array.n_lowest(m["array"], m["3"])
cube.query(m["3 lowest"])
```

## Actual Result

<pre>
com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure 3 lowest on location AllMember
java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure 3 lowest on location AllMember
	at java.base/java.util.concurrent.ForkJoinTask.completeExceptionally(Unknown Source)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.performExceptionalCompletion(CancellableCountedCompleter.java:291)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:278)
	at java.base/java.util.concurrent.CountedCompleter.tryComplete(Unknown Source)
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.afterCompute(ActivePivotVersion.java:1377)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:157)
	at com.quartetfs.biz.pivot.context.impl.ContextualCancellableCountedCompleter.afterExec(ContextualCancellableCountedCompleter.java:124)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:181)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure 3 lowest on location AllMember
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:178)
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.onRegularCompletion(PostProcessedAggregatesRetrieval.java:303)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:263)
	at com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.tryCompleteParents(MultiCancellableCountedCompleter.java:244)
	at com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.onRegularCompletion(MultiCancellableCountedCompleter.java:336)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:263)
	at java.base/java.util.concurrent.CountedCompleter.tryComplete(Unknown Source)
	at com.qfs.store.query.impl.ACompiledTask.afterCompute(ACompiledTask.java:67)
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:157)
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Cannot read 'int' value from an instance of ArrayChunkLongNullable
	at com.qfs.chunk.impl.AWritableArray.readInt(AWritableArray.java:32)
	at com.qfs.column.impl.AChunkedColumn.readInt(AChunkedColumn.java:280)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult$ResultRecordReader.readInt(PointListRetrievalResult.java:3315)
	at com.activeviam.chouket.pivot.measure.operation.AVectorAccessOperation$NthLowest.lambda$getCopperDefinitionFunction$57f39814$1(AVectorAccessOperation.java:166)
	at com.activeviam.copper.operation.operator.Operators$ObjectRecordMapFunction.evaluate(Operators.java:707)
	at com.activeviam.copper.operation.function.TypeConvertedCopperFunction.evaluate(TypeConvertedCopperFunction.java:61)
	at com.activeviam.copper.pivot.pp.MapperPostProcessor.evaluate(MapperPostProcessor.java:77)
	at com.quartetfs.biz.pivot.postprocessing.impl.ABasicPostProcessor$TransformationProcedure.doTransform(ABasicPostProcessor.java:290)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult$AObjectTransformationProcedure.transform(PointListRetrievalResult.java:2774)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult$4.doExecute(PointListRetrievalResult.java:1243)
	at com.quartetfs.biz.pivot.cellset.impl.AInterruptibleValuesProcedure.execute(AInterruptibleValuesProcedure.java:46)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.forEachPoint(PointListRetrievalResult.java:955)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.transformSelfPoints(PointListRetrievalResult.java:1237)
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.transformInto(PointListRetrievalResult.java:1152)
	at com.quartetfs.biz.pivot.cellset.impl.PostProcessedRetrievalResultWriter.transformAndContribute(PostProcessedRetrievalResultWriter.java:227)
	at com.quartetfs.biz.pivot.query.aggregates.impl.AdvancedAggregatesRetriever.transformAndContribute(AdvancedAggregatesRetriever.java:185)
	at com.quartetfs.biz.pivot.postprocessing.impl.ABasicPostProcessor.compute(ABasicPostProcessor.java:199)
	at com.quartetfs.biz.pivot.query.aggregates.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:164)
	... 15 more
</pre>

This is because floor return a long but we expect an int.

## Environment

- atoti: 0.4.3

**Comment by fabiencelier** [comment]
Instead of `reader.readInt` we should do the same as when when read a vector element: 
```java
((Number) reader.read(1)).intValue())
```

**Comment by fabiencelier** [comment]
This will be fixed in the next release (and in continuous build 0.4.4-20200928153045)
