### ISSUE TITLE
Support vectors of large size (100K+ entries)

### ISSUE THREAD

**Issue by OPeyrusse** [atoti/atoti#163]
## Description

In my project, I must load data with vectors of int/double values of size 400,000. When doing so without any special configuration, there is an error:
```python
import atoti as tt
session = tt.create_session()
deal_store = session.read_parquet("vectors.parquet", store_name="deals")
```

> java.lang.IllegalStateException: One cannot allocate a vector of length 400000 in a pool with blocks of size 16384. Please increase the block size for vectors. 
	at com.qfs.vector.impl.ABlockVectorAllocator.allocateNewVector(ABlockVectorAllocator.java:77)
	at com.qfs.chunk.impl.AChunkAllocator$ThreadLocalVectorAllocator.allocateNewVector(AChunkAllocator.java:458)
	at com.qfs.chunk.impl.ChunkVector.allocateVector(ChunkVector.java:223)
	at com.qfs.chunk.impl.ChunkVector.writeNotVector(ChunkVector.java:198)

A workaroud for this is to use the system property `defaultChunkSize` to increase the size of chunks to have enough space to hold my vectors. However, it impacts every chunk in my application, wasting a lot of memory. 
```python
config = tt.config.create_config(java_args=["-DdefaultChunkSize=8388608"])
session = tt.create_session(config=config)
```

## Context

Such a size for vectors is standard when analysing banking data to compute VaR with an internal modeling approach. The vectors contain the results of many simulations. Though the number is very high, it is often filled with a common value, and only a limited number of values - like 10% of the entries in the vectors - have a value different fom that common value.

**Comment by fabiencelier** [comment]
This can be reproduced like that:

```python
import pandas as pd, atoti as tt
array = [ float(i) for i in range(0,40000)] # You might need to increase this limit
df = pd.DataFrame({
    "ID": [1,2],
    "Array": [array, array]
})
session = tt.create_session()
base = session.read_pandas(df,store_name = "sales")
cube = session.create_cube(base)
```

<details>
<summary>One cannot allocate a vector of length 40000 in a pool with blocks of size 32768. Please increase the block size for vectors. </summary>
<pre>
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.activeviam.fwk.ActiveViamRuntimeException: Transaction commit failed
	at com.qfs.store.transaction.ITransactionExceptionHandler.onCommitFailure(ITransactionExceptionHandler.java:47)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2513)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.loadPaths(AFileBasedDataTable.java:74)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.initialLoad(AFileBasedDataTable.java:53)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.initialLoad(AFileBasedDataTable.java:25)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:571)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.lambda$feed$4(SimpleActiveViamSession.java:632)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.feed(SimpleActiveViamSession.java:632)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.startFeeding(SimpleActiveViamSession.java:591)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:464)
	... 12 more
Caused by: com.qfs.store.transaction.DatastoreTransactionException: An exception occurred during the preparation of the commit of the transaction: DatastoreSchemaTransactionInformation{id=1, epoch=null, writableStoreIds=[0], lockedStoresIds=[0], transactionStatistics=null, branch=Base, shadow=false}
	at com.qfs.store.transaction.impl.TransactionManager.doPrepareCommit(TransactionManager.java:900)
	at com.qfs.store.transaction.impl.TransactionManager.commitTransaction(TransactionManager.java:1008)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2511)
	... 21 more
Caused by: com.qfs.fwk.services.InternalServiceException: [500] com.qfs.fwk.services.InternalServiceException: [500] Failed to process update of type  for partition 1 of store `sales`.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at com.qfs.store.impl.MultiVersionDatastoreSchema.doForEachStore(MultiVersionDatastoreSchema.java:837)
	at com.qfs.store.impl.MultiVersionDatastoreSchema.flushStoresTransactions(MultiVersionDatastoreSchema.java:936)
	at com.qfs.store.impl.MultiVersionDatastoreSchema.prepareCommit(MultiVersionDatastoreSchema.java:737)
	at com.qfs.store.transaction.impl.DatastoreSchemaTransactionManager.prepareCommitTransaction(DatastoreSchemaTransactionManager.java:164)
	at com.qfs.store.transaction.impl.TransactionManager.doPrepareCommit(TransactionManager.java:879)
	... 23 more
Caused by: com.qfs.fwk.services.InternalServiceException: [500] Failed to process update of type  for partition 1 of store `sales`.
	at com.qfs.store.impl.StorePartitionWorker$RunConsumer.process(StorePartitionWorker.java:440)
	at com.qfs.store.impl.StorePartitionWorkUnitQueue.consume(StorePartitionWorkUnitQueue.java:187)
	at com.qfs.store.impl.StorePartitionWorker$ProcessingTask.processPendingUnits(StorePartitionWorker.java:387)
	at com.qfs.store.impl.StorePartitionWorker$ProcessingTask.compute(StorePartitionWorker.java:359)
	at java.base/java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: One cannot allocate a vector of length 40000 in a pool with blocks of size 32768. Please increase the block size for vectors. 
	at com.qfs.vector.impl.ABlockVectorAllocator.allocateNewVector(ABlockVectorAllocator.java:77)
	at com.qfs.chunk.impl.AChunkAllocator$ThreadLocalVectorAllocator.allocateNewVector(AChunkAllocator.java:458)
	at com.qfs.chunk.impl.ChunkVector.allocateVector(ChunkVector.java:223)
	at com.qfs.chunk.impl.ChunkVector.writeNotVector(ChunkVector.java:186)
	at com.qfs.chunk.impl.ChunkVector.write(ChunkVector.java:148)
	at com.qfs.store.impl.ChunkSet.write(ChunkSet.java:579)
	at com.qfs.store.impl.ChunkRecordWriter.write(ChunkRecordWriter.java:64)
	at com.qfs.store.record.impl.ARecordFieldHandler$ObjectHandler.transfer(ARecordFieldHandler.java:286)
	at com.qfs.store.record.impl.AFixedSizeRecordBlock$RecordView.transfer(AFixedSizeRecordBlock.java:288)
	at com.qfs.store.impl.ColumnarRecordSet.append(ColumnarRecordSet.java:382)
	at com.qfs.store.impl.ARecordSetTransaction.add(ARecordSetTransaction.java:100)
	at com.qfs.store.impl.StorePartitionTransaction.doAddRecord(StorePartitionTransaction.java:418)
	at com.qfs.store.impl.StorePartitionTransaction.unsafeAddRecord(StorePartitionTransaction.java:327)
	at com.qfs.store.impl.StorePartitionTransaction.addRecord(StorePartitionTransaction.java:268)
	at com.qfs.store.impl.StorePartitionRecordAddUnit.run(StorePartitionRecordAddUnit.java:35)
	at com.qfs.store.impl.StorePartitionWorker$RunConsumer.process(StorePartitionWorker.java:438)
	... 9 more
</pre>
</details>

We need to specify the size of the vector when building the schema by building a VectorFieldDescription with the size instead of a simple FieldDescription.

I see 2 ways to get the size:
  - by inferring it (easy for CSV, might not be as easy for other types)
  - by adding a config, but it adds noise to the API

**Comment by rcolle** [comment]
I think this could be done in the type definition.
We have this definition at the moment: `DOUBLE_ARRAY = DataType("double[]", True)`

We could do something like:
```python
base = session.read_pandas(df,store_name = "sales", types = {"Array" : DataType("double[40000]", True)})
```
