### ISSUE TITLE
Store defined with a column local_date or local_date_time can't load a pandas dataframe setup with datetime object

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#175]
## Steps to reproduce

Notebook attached: 
[DateFormat.zip](https://github.com/atoti/atoti/files/5473913/DateFormat.zip)

## Actual Result

Data is just not loaded. No exception in the notebook but error message in the log (see below)

## Expected Result

Data should be loaded with the correct dates, given that pandas is defined as a date type and the store is defined as date type too... No matter the string format, the date type should be recognized
User is surprised by this behavior

## Environment

- atoti: 0.4.3
- Python: 3.8.5
- Operating System: win32

## Logs (if relevant)

<details>
<summary>Stacktrace from logs</summary>
<pre>
WARNING: [source, parsing, line, csv] WARNING 2020-11-02T09:43:58.809Z uptime=20661ms com.qfs.msg.csv.impl.Parser.onTranslationFailure:493 thread=csv-worker-CSVSource-2 thread_id=70 event_type=CsvLineParsingFailure CSV line parsing failed file=/tmp/atoti-tjfm4ffx/tmp56pow9dt.pdcvs file_line_number=3 file_line=[2020-02-01, ARR3]
com.activeviam.fwk.ActiveViamRuntimeException: Exception while translating column Date with parser Plugin Value (key=LocalDate[yyyyMMdd], class com.quartetfs.fwk.format.impl.LocalDateParser) in file FileSystemFileInfo [fullName=/tmp/atoti-tjfm4ffx/tmp56pow9dt.pdcvs, lastModifiedTime=Mon Nov 02 10:43:58 CET 2020]. Parsed text was "2020-02-01"
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:169)
	at com.qfs.msg.impl.ColumnCalculationContext.processColumn(ColumnCalculationContext.java:159)
	at com.qfs.msg.impl.ColumnCalculationContext.process(ColumnCalculationContext.java:113)
	at com.qfs.msg.impl.ColumnCalculationContext.processTuple(ColumnCalculationContext.java:82)
	at com.qfs.msg.csv.translator.impl.AColumnarTranslator.translateTuple(AColumnarTranslator.java:125)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:26)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:19)
	at com.qfs.source.impl.TupleMessageChunk.append(TupleMessageChunk.java:45)
	at com.qfs.msg.csv.impl.Parser.parse(Parser.java:181)
	at com.qfs.msg.csv.impl.ParserTask.parseIteration(ParserTask.java:387)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:244)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:41)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	at com.qfs.msg.csv.impl.ParserThread.run(ParserThread.java:64)
Caused by: com.activeviam.fwk.ActiveViamRuntimeException: Date parsing of char sequence 2020-02-01 failed. Date pattern was yyyyMMdd.
	at com.quartetfs.fwk.format.impl.ATemporalParser.parse(ATemporalParser.java:84)
	at com.quartetfs.fwk.format.impl.ATemporalParser.parse(ATemporalParser.java:31)
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:161)
	... 16 more
Caused by: java.time.format.DateTimeParseException: Text '2020-02-01' could not be parsed at index 4
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
	at java.base/java.time.LocalDate.parse(Unknown Source)
	at com.quartetfs.fwk.format.impl.LocalDateParser.doParse(LocalDateParser.java:49)
	at com.quartetfs.fwk.format.impl.LocalDateParser.doParse(LocalDateParser.java:21)
	at com.quartetfs.fwk.format.impl.ATemporalParser.parse(ATemporalParser.java:82)
	... 18 more
</pre>
</details>

**Comment by xpilasav** [comment]
I tried with local_date_time too and same issue
>> In cell 8 
```
data_store_date = session.create_store({
    "Date": tt.types.**local_date_time**("yyyyMMdd"),
    "NodeID" : tt.types.STRING,
},keys=["Date", "NodeID"], store_name = "DataDATE")
```

**Comment by fabiencelier** [comment]
When reading from pandas we use the CSV reader so we write the date to string and read it.

> Date parsing of char sequence 2020-02-01 failed. Date pattern was yyyyMMdd.

This is because we always write the date to the `yyyy-MM-dd` format but it reads it with the `yyyyMMdd` format you set in the store. If you change your date field to `"Date": tt.type.local_date("yyyy-MM-dd")` you will be able to read correctly your dataframe.

Any reason you set a specific parser type and not use the default ?

We should try to write and read in the same format. An issue is that pandas only support one `date_format` argument when writing to CSV while atoti can in theory support different format for the same store, but that should be unusual.

> No exception in the notebook but error message in the log

Related to https://github.com/atoti/atoti/issues/64: we are working on a feedback when some parsing fails (warning in the notebook + detailed report)

**Comment by xpilasav** [comment]
I think the point of the question is no matter what date format provided, the conversion local_date (atoti) to datetime (python) should be automatic, no matter what String format we used to setup local_date
