### ISSUE TITLE
Read_parquet can't read empty vector

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#190]
## Steps to reproduce
If you run this code you will get an issue, it is not happening if you load directly from pandas.

```
import atoti as tt
import pandas as pd
session = tt.create_session()
df = pd.DataFrame({
    "l1": [1, 2, 3, 4,5], 
    "l2": [[1.,2.], [1.], [2.,3.], [2.,3.], []]
})

df.to_parquet("./test.parquet")

store = session.read_parquet("./test.parquet", store_name="test")
cube = session.create_cube(store)
```

## Environment

- atoti: 0.4.4.1820.20201120172252
- Python: 3.8.6
- Operating System: win32

## Logs (if relevant)

<details>
<summary>Stacktrace</summary>
<pre>
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.activeviam.fwk.ActiveViamRuntimeException: Failed to parse /home/fabien/workspaces/examples/test.parquet
	at com.activeviam.parquet.impl.ParquetParser.waitForParsingCompletion(ParquetParser.java:741)
	at com.activeviam.parquet.impl.ParquetParser.parse(ParquetParser.java:617)
	at com.activeviam.chouket.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:76)
	at com.activeviam.chouket.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:31)
	at com.activeviam.chouket.util.files.LocalPath.accept(LocalPath.java:171)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataTable.loadPathWithinTransaction(ParquetDataTable.java:123)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.lambda$loadPaths$0(AFileBasedDataTable.java:77)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2431)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.performInTransaction(FlexibleTransactionManager.java:190)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.loadPaths(AFileBasedDataTable.java:74)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.initialLoad(AFileBasedDataTable.java:53)
	at com.activeviam.chouket.loading.impl.AFileBasedDataTable.initialLoad(AFileBasedDataTable.java:25)
	at com.activeviam.chouket.impl.SimpleAtotiManager.loadAndWatchOperation(SimpleAtotiManager.java:516)
	at com.activeviam.chouket.impl.SimpleAtotiManager.lambda$feed$4(SimpleAtotiManager.java:573)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.activeviam.chouket.impl.SimpleAtotiManager.feed(SimpleAtotiManager.java:573)
	at com.activeviam.chouket.impl.SimpleAtotiManager.startFeeding(SimpleAtotiManager.java:532)
	at com.activeviam.chouket.impl.SimpleAtotiManager.refresh(SimpleAtotiManager.java:421)
	at com.activeviam.chouket.AtotiSession.refresh(AtotiSession.java:76)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: org.apache.parquet.io.ParquetDecodingException: Failed to read from input stream
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.activeviam.parquet.impl.ParquetParser.waitForParsingCompletion(ParquetParser.java:739)
	... 30 more
Caused by: org.apache.parquet.io.ParquetDecodingException: Failed to read from input stream
	at com.activeviam.parquet.impl.vectorized.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:1103)
	at com.activeviam.parquet.impl.vectorized.VectorizedRleValuesReader.readLists(VectorizedRleValuesReader.java:917)
	at com.activeviam.parquet.impl.vectorized.VectorizedRleValuesReader.readDictionarizedListValues(VectorizedRleValuesReader.java:394)
	at com.activeviam.parquet.impl.vectorized.VectorizedColumnReader.readDictionarizedValues(VectorizedColumnReader.java:307)
	at com.activeviam.parquet.impl.vectorized.VectorizedColumnReader.readBatch(VectorizedColumnReader.java:224)
	at com.activeviam.parquet.impl.vectorized.VectorizedParquetRecordReader.nextBatch(VectorizedParquetRecordReader.java:252)
	at com.activeviam.parquet.impl.vectorized.VectorizedParquetRecordReader.readNextRecord(VectorizedParquetRecordReader.java:194)
	at com.activeviam.parquet.impl.vectorized.VectorizedParquetRecordReader.read(VectorizedParquetRecordReader.java:180)
	at com.activeviam.parquet.impl.ParquetParser.parseInOneThread(ParquetParser.java:396)
	at com.activeviam.parquet.impl.ParquetParser.parseInOneThread(ParquetParser.java:280)
	at com.activeviam.parquet.impl.ParquetParser.lambda$parse$3(ParquetParser.java:608)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.EOFException
	at org.apache.parquet.bytes.SingleBufferInputStream.read(SingleBufferInputStream.java:52)
	at com.activeviam.parquet.impl.vectorized.VectorizedRleValuesReader.readUnsignedVarInt(VectorizedRleValuesReader.java:1017)
	at com.activeviam.parquet.impl.vectorized.VectorizedRleValuesReader.readNextGroup(VectorizedRleValuesReader.java:1076)
	... 14 more
</pre>
</details>

**Comment by alexis-bvq** [comment]
after debugging a little more the issue is not due to empty value but due to 0.0:
```
import atoti as tt
import pandas as pd
session = tt.create_session()
df = pd.DataFrame({
    "l1": [1, 2, 3, 4,5], 
    "l2": [[1.,2.], [1.], [2.,3.], [2.,3.], [0.0]]
})

df.to_parquet("./test.parquet")

store = session.read_parquet("./test.parquet", store_name="test")
cube = session.create_cube(store)
```
Nevertheless, if the first vectors have a size of one, the bug is not happening:
```
import atoti as tt
import pandas as pd
session = tt.create_session()
df = pd.DataFrame({
    "l1": [1, 2, 3, 4,5], 
    "l2": [[1.], [1.], [2.,3.], [2.,3.], [0.0]]
})

df.to_parquet("./test.parquet")

store = session.read_parquet("./test.parquet", store_name="test")
cube = session.create_cube(store)
```

**Comment by fabiencelier** [comment]
Thank you for reporting the issue !
I have opened an internal ActivePivot ticket [PIVOT-4503](https://support.activeviam.com/jira/browse/PIVOT-4503)

**Comment by fabiencelier** [comment]
This will be fixed in the next release
