### ISSUE TITLE
AtotiJavaException: Illegal character in: created date

### ISSUE THREAD

**Issue by veonua** [atoti/atoti#242]
## Steps to reproduce

the code that uses pandas works well
```
df = pd.read_parquet("./data/reddit.parquet") 
reddit_store = session.read_pandas(df, keys=["_id"], store_name="Reddit_Posts")
```

 in the same time following code fails 
`reddit_store = session.read("./data/reddit.parquet", keys=["_id"], store_name="Reddit_Posts")`

## Actual Result

```
INFO: Python connection started.
Feb 16, 2021 8:03:43 PM py4j.reflection.MethodInvoker invoke
WARNING: Exception occurred in client code.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.avro.SchemaParseException: Illegal character in: created date
	at org.apache.avro.Schema.validateName(Schema.java:1532)
	at org.apache.avro.Schema.access$400(Schema.java:87)
	at org.apache.avro.Schema$Field.(Schema.java:520)
	at org.apache.avro.Schema$Field.(Schema.java:559)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:264)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:248)
	at io.atoti.loading.parquet.visitor.ParquetDiscoveryPathVisitor.discover(ParquetDiscoveryPathVisitor.java:83)
	at io.atoti.loading.parquet.visitor.ParquetDiscoveryPathVisitor.visit(ParquetDiscoveryPathVisitor.java:58)
	at io.atoti.loading.parquet.visitor.ParquetDiscoveryPathVisitor.visit(ParquetDiscoveryPathVisitor.java:44)
	at io.atoti.util.files.LocalPath.accept(LocalPath.java:174)
	at io.atoti.loading.parquet.impl.ParquetDataTable.init(ParquetDataTable.java:97)
	at io.atoti.loading.parquet.impl.ParquetDataTable.getOrCreateInfo(ParquetDataTable.java:208)
	at io.atoti.loading.parquet.impl.ParquetDataTable.getSchema(ParquetDataTable.java:204)
	at io.atoti.loading.parquet.impl.ParquetDataSource.getTableSchema(ParquetDataSource.java:55)
	at io.atoti.loading.impl.ASingleTableSourceWithSchema.createStore(ASingleTableSourceWithSchema.java:41)
	at io.atoti.api.impl.AtotiApiImpl.createStoreFromDataSource(AtotiApiImpl.java:108)
```

## Environment

- atoti: 0.5.1
- Python: 3.8.0
- Operating System: linux

**Comment by tibdex** [comment]
Hi Andrew, can you share the data and code that you used so that we can try to reproduce this?

**Comment by Skyscimitar** [comment]
Hello,

The problem comes from the column name `created date` which contains a space. The Java implementation of parquet only supports alphanumeric characters in column names (and `_`), therefore the column `created date` which contains a space cannot be read by the Java parquet parser. To use this parquet file with atoti you will have to rename the columns before loading the file.

Here is the relevant pull request on the parquet repo: https://github.com/apache/parquet-mr/pull/361

I'm postponing this issue until the change is merged into the parquet library.
