### ISSUE TITLE
Unable to read parquet file using s3 addressing scheme

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#27]
## Description
I am able to perform csv read using
```
asset_positions_store = session.read_csv(
    "s3://data.atoti.io/notebooks/collateral-shortfall-monitoring/assets_positions.csv",
    keys=["Account", "Asset_Code"],
    store_name="asset_positions_store",
)
```
I tried to do the same for parquet:
```
assets_store = session.read_parquet(
    "s3://data.atoti.io/notebooks/collateral-shortfall-monitoring/assets_attributes.parquet",
    keys=["Asset_Code"],
    store_name="assets_store",
)
```
I encountered the below error:
```
Py4JJavaError: An error occurred while calling o2.createStoreFromParquet.
: java.lang.IllegalArgumentException: Wrong FS: s3://data.atoti.io/notebooks/collateral-shortfall-monitoring/assets_attributes.parquet, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:773)
	at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:86)
	at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:447)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1804)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1849)
	at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:675)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDiscovery.doGetSingleFile(ParquetDiscovery.java:100)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDiscovery.getSingleFile(ParquetDiscovery.java:80)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDiscovery.getSchemaFromParquetFile(ParquetDiscovery.java:58)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataLoaderImpl.createDataTable(ParquetDataLoaderImpl.java:85)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataLoaderImpl.createStore(ParquetDataLoaderImpl.java:102)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataStoreOperation.createDataTable(ParquetDataStoreOperation.java:73)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataStoreOperation.lambda$load$0(ParquetDataStoreOperation.java:53)
	at java.base/java.util.Collections$SingletonMap.forEach(Collections.java:4946)
	at com.activeviam.chouket.loading.parquet.impl.ParquetDataStoreOperation.load(ParquetDataStoreOperation.java:50)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.createStoreFromParquet(ActiveViamSessionApiImpl.java:363)
```

## Context
- Atoti version: 0.3.1
- Python version: 3.7.6
- Operating System: Windows 10 Pro

**Comment by fabiencelier** [comment]
Hello,
ActivePivot does not support natively loading parquet file from the cloud. Here is the internal issue for it: [PIVOT-4290](https://support.activeviam.com/jira/browse/PIVOT-4290)
Once it's available we will add it to atoti.

**Comment by fabiencelier** [comment]
Parquet on S3 will be available in the next release !!
