### ISSUE TITLE
Can't use Atoti even after an upgrade due to licensing

### ISSUE THREAD

**Issue by ArthurZ** [atoti/atoti#365]
# Issue: I upgraded Atoti, but still can't use it in Spyder nor Jupyter:
Welcome to atoti 0.4.3!

By using this community edition, you agree with the license available at https://www.atoti.io/eula.
Browse the official documentation at https://docs.atoti.io.
Join the community at https://www.atoti.io/register.

You can hide this message by setting the ATOTI_HIDE_EULA_MESSAGE environment variable to True.
Traceback (most recent call last):

  File "C:\Users\ar\AppData\Local\Temp/ipykernel_13696/2960781956.py", line 1, in <module>
    import atoti as at

  File "C:\Users\aranaconda3\lib\site-packages\atoti\__init__.py", line 31, in <module>
    check_license(_EDITION, _LICENSE_END_DATE)

  File "C:\Users\ar\anaconda3\lib\site-packages\atoti\_licensing.py", line 146, in check_license
    raise Exception(output.content)

Exception: To keep using atoti, update to atoti's latest version or upgrade to Atoti+.

## Steps to reproduce
Code `import atoti as at`

## Actual Result
Error above

## Expected Result
Can use
## Environment
Win 10 64 Bit Pro Anaconda with the latest updates

- Python: 3.8.11
- Operating System: win32

**Comment by ArthurZ** [comment]
Never mind. I need to uninstall it, then install it, The issue was gone then. It looks like the update did not take care of the older version. Still maybe a bug there.
