### ISSUE TITLE
Setup simulation levels must be of type string

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#37]
## Steps to reproduce

Create a simulation using `setup_simulation` and have one of the levels be of type different than string:

```python
import pandas as pd

dummy = {
    "id": [0, 1, 2, 3],
    "Name": ["John", "John", "Thomas", "Mike"],
    "Score": [10, 8, 5, 12],
}
dummy_df = pd.DataFrame(data=dummy)

import atoti

session = atoti.create_session()
dummy_store = session.read_pandas(dummy_df, keys=["id"])
cube = session.create_cube(dummy_store)

cube.measures["Score"] = atoti.agg.sum(dummy_store["Score"])

simulation = cube.setup_simulation(
    'DUMMY_SIMU',
    levels=[cube.levels["id"]],
    replace=[cube.measures["Score"]]
)
```

## Actual Result

> java.lang.ClassCastException: Incorrect type String for tuple with value id for lookup in dictionary of type ChristmasDictionaryLong. Exception in store: DUMMY_SIMU, field: id, for tuple: [id, Base, null, 1.0].

```
Traceback (most recent call last):
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/exceptions.py", line 219, in catch_py4j_exceptions
    return method(*args, **kwargs)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/_java_api.py", line 142, in refresh
    self.java_session.refresh(force_start)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/vendor/atotipy4j/java_gateway.py", line 1313, in __call__
    return_value = get_return_value(
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/vendor/atotipy4j/protocol.py", line 322, in get_return_value
    raise Py4JJavaError(
Py4JJavaError: An error occurred while calling t.refresh.
: java.lang.ClassCastException: Incorrect type String for tuple with value id for lookup in dictionary of type ChristmasDictionaryLong. Exception in store: DUMMY_SIMU, field: id, for tuple: [id, Base, null, 1.0].
	at com.qfs.store.transaction.impl.TransactionManager.transformToFullRecords(TransactionManager.java:1375)
	at com.qfs.store.transaction.impl.TransactionManager.addAll(TransactionManager.java:1136)
	at com.qfs.store.transaction.impl.DelegatingOpenedTransaction.addAll(DelegatingOpenedTransaction.java:132)
	at com.qfs.store.transaction.ITransactionalWriter.addAll(ITransactionalWriter.java:117)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.lambda$initialLoad$0(PojoDataTable.java:60)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2492)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.initialLoad(PojoDataTable.java:58)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.initialLoad(PojoDataTable.java:26)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.lambda$feed$3(SimpleActiveViamSession.java:629)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.feed(SimpleActiveViamSession.java:629)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.startFeeding(SimpleActiveViamSession.java:588)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:385)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-5-f9a59dd0d932>", line 1, in <module>
    simulation = cube.setup_simulation(
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/cube.py", line 218, in setup_simulation
    simulation = Simulation(
  File "<string>", line 11, in __init__
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/simulation.py", line 114, in __post_init__
    self._java_api.refresh()
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/exceptions.py", line 221, in catch_py4j_exceptions
    raise AtotiJavaException(
AtotiJavaException: An error occurred in the JVM:
An error occurred while calling t.refresh.
: java.lang.ClassCastException: Incorrect type String for tuple with value id for lookup in dictionary of type ChristmasDictionaryLong. Exception in store: DUMMY_SIMU, field: id, for tuple: [id, Base, null, 1.0].
	at com.qfs.store.transaction.impl.TransactionManager.transformToFullRecords(TransactionManager.java:1375)
	at com.qfs.store.transaction.impl.TransactionManager.addAll(TransactionManager.java:1136)
	at com.qfs.store.transaction.impl.DelegatingOpenedTransaction.addAll(DelegatingOpenedTransaction.java:132)
	at com.qfs.store.transaction.ITransactionalWriter.addAll(ITransactionalWriter.java:117)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.lambda$initialLoad$0(PojoDataTable.java:60)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2492)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.initialLoad(PojoDataTable.java:58)
	at com.activeviam.chouket.loading.pojo.PojoDataTable.initialLoad(PojoDataTable.java:26)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.lambda$feed$3(SimpleActiveViamSession.java:629)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.feed(SimpleActiveViamSession.java:629)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.startFeeding(SimpleActiveViamSession.java:588)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:385)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Expected Result

I would expect it to work. If not I would expect it to be documented with a better feedback.

Workaround is to force the type to string:

```python
dummy_store = session.read_pandas(
    dummy_df, keys=["id"], type={"id": atoti.types.STRING}
)
```

## Environment

- Atoti: 0.4.0.20200512194154
- Python: 3.8.2
- Operating System: linux

**Comment by Skyscimitar** [comment]
Hello! We have a fix for this on the way! It should be available soon. It will also come with the ability to use wildcard values any type of simulation fields.
