### ISSUE TITLE
Random SocketTimeOut errors in Java server

### ISSUE THREAD

**Issue by vrotival** [atoti/atoti#377]
## Steps to reproduce

Happens usually when trying to edit cube data once it was created, e.g (sorry for the code truncations for confidentiality)

    session = tt.create_session(name=Config.system,
                                config=dict(port=Config.port,
                                            user_content_storage=os.path.join(Config.confFolder, f"content_{Config.system}.db")))

    t_store = session.read_pandas(dataframe=data_enriched, table_name=Config.system)

    cube = session.create_cube(t_store)

    measures = cube.measures
    hierarchies = cube.hierarchies
    levels = cube.levels

[then exceptions occur usually in either of these lines]

            for c in r_components.keys():
                c_name = f"{c}_bucket"
                hierarchies[c] = [typhoon_store[c]]
                for m in [k for k in measures if k.startswith(c_name)]:
                    del measures[m]

or

    for m in measures:
        if m.startswith("Toto"):
            measures[m].folder = "Folder"
        elif not any([m.startswith(k) for k in ["toto", "titi"]]):
            measures[m].visible = False

        name_added = m.replace("Toto", "Titi").replace(".SUM", "")
        measures[name_added] = measures[m] / measures[m[:4]]
        measures[name_added].folder = measures[m].folder

## Actual Result

com.activeviam.fwk.ActiveViamRuntimeException: java.io.IOException: java.net.SocketTimeoutException
        at io.atoti.rest.AtotiWebSocketConfig$1.handleTransportError(AtotiWebSocketConfig.java:72) ~[server-common-0.6.0.jar!/:0.6.0]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleTransportError(WebSocketHandlerDecorator.java:80) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleTransportError(LoggingWebSocketHandlerDecorator.java:64) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleTransportError(ExceptionWebSocketHandlerDecorator.java:68) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onError(StandardWebSocketHandlerAdapter.java:157) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:626) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:498) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:322) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:251) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:224) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106) ~[spring-websocket-5.3.3.jar!/:5.3.3]
        at io.atoti.rest.AtotiWebSocketConfig.lambda$registerWebSocketHandlers$0(AtotiWebSocketConfig.java:44) ~[server-common-0.6.0.jar!/:0.6.0]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at io.atoti.rest.AtotiWebSocketConfig.lambda$registerWebSocketHandlers$1(AtotiWebSocketConfig.java:41) ~[server-common-0.6.0.jar!/:0.6.0]
        at io.atoti.impl.SimpleAtotiManager.publishMeasures(SimpleAtotiManager.java:284) ~[patachou-core-0.6.0.jar!/:0.6.0]
        at io.atoti.api.impl.OutsideTransactionAtotiApi.publishMeasures(OutsideTransactionAtotiApi.java:470) ~[patachou-core-0.6.0.jar!/:0.6.0]
        at io.atoti.api.impl.AtotiApiImpl.publishMeasures(AtotiApiImpl.java:408) ~[patachou-core-0.6.0.jar!/:0.6.0]
        at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) ~[py4j-0.10.9.jar!/:na]
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) ~[py4j-0.10.9.jar!/:na]
        at py4j.Gateway.invoke(Gateway.java:282) ~[py4j-0.10.9.jar!/:na]
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) ~[py4j-0.10.9.jar!/:na]
        at py4j.commands.CallCommand.execute(CallCommand.java:79) ~[py4j-0.10.9.jar!/:na]
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182) ~[py4j-0.10.9.jar!/:na]
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106) ~[py4j-0.10.9.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.io.IOException: java.net.SocketTimeoutException
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:324) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:259) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:613) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41]
        ... 24 common frames omitted
Caused by: java.net.SocketTimeoutException: null
        at org.apache.tomcat.util.net.NioEndpoint$Poller.timeout(NioEndpoint.java:975) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:751) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
        ... 1 common frames omitted

## Environment

- atoti:
- Python:
- Operating System:

**Comment by bloussou** [comment]
Hello,
We were not able to reproduce this. Feel free to reopen it if you still have the issue with the latest version
