### ISSUE TITLE
ActivePivot Server down during S3 data loading

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#400]
##Description
I have tested 2 ways to retrieve CSV files from a S3 bucket.
1) All the 60 files (1.1 GB / file) at the same time, and the ActivePivot server went down during the data loading after reaching the maximum heap size (I did not see anything on the logs)
2) Loading year by year, 12 files per 12 files by using a loop and another file pattern. This one worked well!

## Expected Result
Even considering that the second way is recommended, and even considering that the first way may be "easier" for the server if I pull compressed CSV files, I think the ActivePivot server should go down during the process.

## Environment
- atoti: 0.6.2
- Python: 3.9.6
- Operating System: linux

**Comment by rcolle** [comment]
> All the 60 files (1.1 GB / file) at the same time, and the ActivePivot server went down during the data loading after reaching the maximum heap size (I did not see anything on the logs).

Isn't this still caused by the lack of off-heap memory tracking due to the core ActivePivot bug you've recently encountered?
Do you still see the same issue when using either of the following **debug** options:

- `-DchunkAllocatorClass=com.qfs.chunk.array.impl.ArrayChunkAllocator`
- `-DchunkAllocatorClass=com.qfs.chunk.buffer.impl.DirectBufferChunkAllocator`

**Comment by Harold7665** [comment]
The server goes down with the option `-DchunkAllocatorClass=com.qfs.chunk.array.impl.ArrayChunkAllocator`.
However I have logs atoti side and activepivot side (https://drive.google.com/drive/folders/1LFqjx-ezsW1EiOM9f_-Sbr_CuaIhXWQv?usp=sharing).
```python
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/lib/python3.9/site-packages/atoti/_type_utils.py in typechecked_func_wrapper(*args, **kwargs)
    184 
    185             # Call the actual function.
--> 186             return self._func(*args, **kwargs)
    187 
    188         # Mark the function as typechecked and return it.

~/miniconda3/lib/python3.9/site-packages/atoti/_docs_utils.py in wrapper(*args, **kwargs)
     14         @wraps(func)
     15         def wrapper(*args: Any, **kwargs: Any) -> Callable:
---> 16             return func(*args, **kwargs)
     17 
     18         # Collecting docstring and docstring templates

~/miniconda3/lib/python3.9/site-packages/atoti/table.py in load_csv(self, path, separator, encoding, process_quotes, array_separator, date_patterns, client_side_encryption)
    271         path, pattern = _split_path_and_pattern(path, ".csv")
    272 
--> 273         CsvDataSource(self._java_api).load_csv_into_table(
    274             path,
    275             self,

~/miniconda3/lib/python3.9/site-packages/atoti/_sources/csv.py in load_csv_into_table(self, path, table, scenario_name, separator, encoding, process_quotes, array_separator, pattern, date_patterns, client_side_encryption)
    109             client_side_encryption=client_side_encryption,
    110         )
--> 111         self.load_data_into_table(
    112             table.name,
    113             scenario_name=scenario_name,

~/miniconda3/lib/python3.9/site-packages/atoti/_sources/__init__.py in load_data_into_table(self, table_name, scenario_name, source_params)
     39             source_params: The parameters specific to the source.
     40         """
---> 41         self._java_api.load_data_into_table(
     42             table_name=table_name,
     43             source_key=self.source_key,

~/miniconda3/lib/python3.9/site-packages/atoti/exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     76                 else f"{java_api.get_throwable_root_cause(java_exception.java_exception)}"
     77             )
---> 78             raise AtotiJavaException(
     79                 cause,
     80                 java_traceback=str(java_exception),

AtotiJavaException: The parsing of some files has failed: [com.activeviam.msg.csv.impl.CloudCsvDataProvider@200bf7ba, com.activeviam.msg.csv.impl.CloudCsvDataProvider@b0d5df6, com.activeviam.msg.csv.impl.CloudCsvDataProvider@14056b5d, com.activeviam.msg.csv.impl.CloudCsvDataProvider@103a180c, com.activeviam.msg.csv.impl.CloudCsvDataProvider@6f739b96, com.activeviam.msg.csv.impl.CloudCsvDataProvider@e709963, com.activeviam.msg.csv.impl.CloudCsvDataProvider@31105473, com.activeviam.msg.csv.impl.CloudCsvDataProvider@71aac025, com.activeviam.msg.csv.impl.CloudCsvDataProvider@2f65aad, com.activeviam.msg.csv.impl.CloudCsvDataProvider@8476011, com.activeviam.msg.csv.impl.CloudCsvDataProvider@3bc71ea6, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1ccb5a13, com.activeviam.msg.csv.impl.CloudCsvDataProvider@2c585815, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1f2cf267, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1c1ded0a, com.activeviam.msg.csv.impl.CloudCsvDataProvider@5ac03758, com.activeviam.msg.csv.impl.CloudCsvDataProvider@34b644e5, com.activeviam.msg.csv.impl.CloudCsvDataProvider@4c7137de, com.activeviam.msg.csv.impl.CloudCsvDataProvider@3ff7f6e7, com.activeviam.msg.csv.impl.CloudCsvDataProvider@64566cb6, com.activeviam.msg.csv.impl.CloudCsvDataProvider@62419db5, com.activeviam.msg.csv.impl.CloudCsvDataProvider@274b89e4, com.activeviam.msg.csv.impl.CloudCsvDataProvider@270b0324, com.activeviam.msg.csv.impl.CloudCsvDataProvider@70efe8af, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1ead6f32, com.activeviam.msg.csv.impl.CloudCsvDataProvider@65d2c1aa, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1abffc17, com.activeviam.msg.csv.impl.CloudCsvDataProvider@159ac57f, com.activeviam.msg.csv.impl.CloudCsvDataProvider@603bfc01, com.activeviam.msg.csv.impl.CloudCsvDataProvider@1317ae3d, com.activeviam.msg.csv.impl.CloudCsvDataProvider@76adb70c, com.activeviam.msg.csv.impl.CloudCsvDataProvider@355f259b, com.activeviam.msg.csv.impl.CloudCsvDataProvider@abb1cc5, com.activeviam.msg.csv.impl.CloudCsvDataProvider@24732de9, com.activeviam.msg.csv.impl.CloudCsvDataProvider@3ffdebbc, com.activeviam.msg.csv.impl.CloudCsvDataProvider@73c27225]
```

**Comment by fabiencelier** [comment]
After seeing this error message I have open this related core issue: https://support.activeviam.com/jira/browse/PIVOT-5118

**Comment by rcolle** [comment]
In your latest logs the server doesn't go down, it simply runs out of memory.

See 
```2021-11-03 11:19:47.083  INFO 26185 --- [csv-worker-CSVSource-7] com.qfs.msg.impl.LogMessageHandler       : CloudFileInfo [fullName=S3EntityPath [name=sample_data_csv/historical_data/data 2017-11.csv, bucket=xxxx], lastModifiedTime=Tue Nov 02 16:13:49 UTC 2021] message finished
2021-11-03 11:19:47.082 ERROR 26185 --- [Catalina-utility-2] o.a.coyote.http11.Http11NioProtocol      : Error processing async timeouts

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source) ~[na:na]
	at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:626) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.AbstractProtocol$1.run(AbstractProtocol.java:609) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

This is probably caused by the fact that atoti processes all the files in a single transaction, instead of doing one transaction per year in the second case.

**Comment by rcolle** [comment]
It would be interesting to get a flight recording and a heap dump at some point during the loading to see where the data is being retained.

**Comment by Harold7665** [comment]
I have added better logs + flight recording to the drive.

**Comment by rcolle** [comment]
Can you also please upload the requested heap dump? That's where we'll get the most info.

**Comment by rcolle** [comment]
@Harold7665 I just saw that you use the following options:
```
-Xms35g -Xmx35g
-XX:MaxDirectMemorySize=65g
-DchunkAllocatorClass=com.qfs.chunk.array.impl.ArrayChunkAllocator
```

Since the array chunk allocator stores everything on heap, the application only has access to 35GB of memory.

**Comment by Harold7665** [comment]
Oh...
I will provide you new flight recording, logs and heap dump with 100 GiB on Xmx.

**Comment by Harold7665** [comment]
Hello,

I have loaded a few more files with 100GiB + ArrayChunkAllocator:
- JFR + logs while loading the historical data (5 years) before the "end", memory was around 65% of maximum.
- Logs at the "end", the server was only doing GC (160gc per minute) + OOM when I tried to stop the data loading from the notebook ; I was not able to get the JFR of this one.

The heapdump is being uploaded.
