### ISSUE TITLE
Error when redefining measure after changing level comparator

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#423]
## Description

The documentation on https://docs.atoti.io/latest/lib/atoti.scope.html#atoti.scope.cumulative wasn't clear to me until @Skyscimitar explained to me.

It would be great to highlight or illustrate with an example that the parameter for the window is intended to be `(n_previous_member, n_next_member)` and that the left parameter should be negative (the corresponding right parameter has to be `None`):
`window=("-5D", None)`

Likewise, the parameter on the right side can only be positive (the corresponding left side has to be `None`):
`window=(None, "5D")`

_Since it must be either negative or positive, and doesn't accept a range, why don't we have a single parameter instead? If it is 5 number of days before current member, then `window="-5D"`. If it is 5 number of days after current member, then `window="5D"`._

This brings to the question, is `window=range(-1, 5)` a valid range (I encountered exception when I tried this).

**Comment by tibdex** [comment]
> It would be great to highlight or illustrate with an example that the parameter for the window is intended to be (n_previous_member, n_next_member) and that the left parameter should be negative

It's already the case:

<img width="1123" alt="Screen Shot 2021-12-01 at 19 27 10" src="https://user-images.githubusercontent.com/6574550/144292303-2727d1a7-2994-4757-84e4-7eb9a884c2e0.png">

> the corresponding right parameter has to be None

No it doesn't have to, you can use windows such as `("-5D", "5D")`.

> Likewise, the parameter on the right side can only be positive (the corresponding left side has to be None)

Again, no: the before and after offsets are not exclusive.

> is window=range(-1, 5) a valid range (I encountered exception when I tried this)

Yes it should be valid. Can you share a minimal reproduction case that raises the error you saw?

**Comment by HuifangYeo** [comment]
Hi @tibdex,

I think the exception is related to https://github.com/atoti/atoti/issues/424. I get it when I had ordered the date in descending order.

[cumulative_range.zip](https://github.com/atoti/atoti/files/7638894/cumulative_range.zip)

**Comment by tibdex** [comment]
Indeed in your notebook, the definition of:

```python
m["cumulative_txn2"] = tt.agg.sum(
    m["contributors.COUNT"], scope=tt.scope.cumulative(l["trans_date"], window=range(-1, 5), dense=True)
)
```

works fine but after doing:

```python
l["trans_date"].comparator = tt.comparator.DESCENDING
```

redefining the same measure throws an exception with the following stack trace:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/tibdex/work/atoti/python/atoti/atoti/_type_utils.py", line 186, in typechecked_func_wrapper
    return self._func(*args, **kwargs)
  File "/Users/tibdex/work/atoti/python/atoti/atoti/measures.py", line 81, in __setitem__
    self.update({key: value})
  File "/Users/tibdex/work/atoti/python/atoti/atoti/_type_utils.py", line 186, in typechecked_func_wrapper
    return self._func(*args, **kwargs)
  File "/Users/tibdex/work/atoti/python/atoti/atoti/measures.py", line 90, in update
    self._update(full_mapping)
  File "/Users/tibdex/work/atoti/python/atoti/atoti/measures.py", line 112, in _update
    self._java_api.publish_measures(self._cube.name)
  File "/Users/tibdex/work/atoti/python/atoti/atoti/exceptions.py", line 82, in catch_py4j_exceptions
    ) from None
atoti.exceptions.AtotiJavaException: An error occurred while calling o235.publishMeasures.
: java.lang.NullPointerException
	at com.activeviam.copper.CubeHelper.retrieveExistingMeasureByName(CubeHelper.java:207)
	at com.activeviam.copper.MeasurePublisher.retrieveMeasureDescription(MeasurePublisher.java:507)
	at com.activeviam.copper.impl.DataCubeContext.retrieveMeasureDescription(DataCubeContext.java:202)
	at com.activeviam.copper.measure.NamedMeasure.getType(NamedMeasure.java:66)
	at com.activeviam.copper.graph.visitor.impl.CalculatedMeasureMerger.tryToMergeWithChildren(CalculatedMeasureMerger.java:145)
	at com.activeviam.copper.graph.visitor.impl.CalculatedMeasureMerger.visitAndGetNewNode(CalculatedMeasureMerger.java:77)
	at com.activeviam.copper.graph.visitor.ACopperTreeRewriter.visit(ACopperTreeRewriter.java:62)
	at com.activeviam.copper.graph.visitor.ACopperTreeRewriter.visit(ACopperTreeRewriter.java:22)
	at com.activeviam.copper.graph.visitor.CopperTreeUtils.walkBfs(CopperTreeUtils.java:46)
	at com.activeviam.copper.graph.visitor.ACopperTreeRewriter.rewrite(ACopperTreeRewriter.java:95)
	at com.activeviam.copper.MeasureOptimizer.rewriteTree(MeasureOptimizer.java:72)
	at com.activeviam.copper.MeasureOptimizer.lambda$optimize$2(MeasureOptimizer.java:59)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at com.activeviam.copper.MeasureOptimizer.optimize(MeasureOptimizer.java:54)
	at com.activeviam.copper.MeasurePublisher.optimizeAndPublish(MeasurePublisher.java:229)
	at com.activeviam.copper.MeasurePublisher.publish(MeasurePublisher.java:181)
	at com.activeviam.copper.impl.DataCubeContext.publish(DataCubeContext.java:227)
	at com.activeviam.copper.measure.BaseCopperMeasure.publish(BaseCopperMeasure.java:113)
	at com.activeviam.copper.measure.BaseCopperMeasure.publish(BaseCopperMeasure.java:61)
	at io.atoti.pivot.measure.impl.AMeasure.doPublish(AMeasure.java:161)
	at io.atoti.pivot.measure.impl.AMeasure.publish(AMeasure.java:130)
	at io.atoti.pivot.measure.impl.AMeasure.doPublish(AMeasure.java:144)
	at io.atoti.pivot.measure.impl.AMeasure.publish(AMeasure.java:130)
	at io.atoti.pivot.measure.MeasureManagerImpl.publishCopper(MeasureManagerImpl.java:443)
	at io.atoti.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:28)
	at io.atoti.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:11)
	at com.activeviam.copper.CopperDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CopperDescriptionPostProcessor.java:93)
	at io.atoti.pivot.impl.CubeImpl$CopperActivePivotDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CubeImpl.java:731)
	at com.activeviam.copper.CopperDescriptionPostProcessor.postProcessActivePivotDescription(CopperDescriptionPostProcessor.java:63)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchemaBuilder.postProcess(ActivePivotSchemaBuilder.java:1030)
	at com.quartetfs.biz.pivot.impl.ActivePivotManagerBuilder.postProcess(ActivePivotManagerBuilder.java:267)
	at io.atoti.pivot.impl.CubeManager.toManagerDesc(CubeManager.java:118)
	at io.atoti.impl.SimpleManager.includePivotChangesToDatastore(SimpleManager.java:424)
	at io.atoti.impl.SimpleManager.refresh(SimpleManager.java:300)
	at io.atoti.impl.SimpleManager.publishMeasures(SimpleManager.java:270)
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.publishMeasures(OutsideTransactionDataApiImpl.java:367)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by bloussou** [comment]
Hello,
This will be fixed in the next release :)
