### ISSUE TITLE
Error when creating array measure with mixed int and float: "Unsupported vector type. Received vector of Object"

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#440]
## Steps to reproduce

This works:
```python
m["int array"] = [10,20,30]
m["float array"] = [10.0, 20.0, 30.0]
```
But this fails:
```python
m["mix array"] = [10.0, 20, 30]
```

## Actual Result

<pre>
AtotiJavaException: An error occurred while calling o102.publishMeasures.
: java.lang.IllegalArgumentException: Unsupported vector type. Received vector of Object
	at com.activeviam.copper.api.Copper.constant(Copper.java:469)
	at io.atoti.pivot.measure.impl.LiteralMeasure.getCopperMeasure(LiteralMeasure.java:34)
	at io.atoti.pivot.measure.impl.AMeasure.doPublish(AMeasure.java:147)
	at io.atoti.pivot.measure.impl.AMeasure.publish(AMeasure.java:130)
	at io.atoti.pivot.measure.MeasureManagerImpl.publishCopper(MeasureManagerImpl.java:443)
	at io.atoti.pivot.measure.MeasureManagerImpl.lambda$publishPendingMeasures$2(MeasureManagerImpl.java:457)
	at com.activeviam.pivot.structure.impl.WritablePivotSchemaStructure.addCalculations(WritablePivotSchemaStructure.java:188)
	at com.activeviam.pivot.structure.impl.ActivePivotManagerUpdater$CubeUpdater.withCalculations(ActivePivotManagerUpdater.java:319)
	at io.atoti.pivot.measure.MeasureManagerImpl.publishPendingMeasures(MeasureManagerImpl.java:457)
	at io.atoti.pivot.impl.CubeImpl.lambda$publishMeasures$11(CubeImpl.java:704)
	at com.quartetfs.biz.pivot.impl.StructuralManagerTransaction.update(StructuralManagerTransaction.java:66)
	at com.quartetfs.biz.pivot.IInternalActivePivotManager.updateStructure(IInternalActivePivotManager.java:36)
	at io.atoti.pivot.impl.CubeImpl.publishMeasures(CubeImpl.java:701)
	at io.atoti.impl.SimpleManager.publishMeasures(SimpleManager.java:325)
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.publishMeasures(OutsideTransactionDataApiImpl.java:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
</pre>

## Expected Result

It is not a big deal but I would expect the measure to be created as a double array

## Environment

- atoti: 0.6.3.dev0
- Python: 3.8.5
- Operating System: linux

**Comment by bloussou** [comment]
Hello @fabiencelier ,
It will be fixed in the next release
