### ISSUE TITLE
Encountered Issue updating schema during measure creation

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#460]
## Steps to reproduce

The error `[500] Issue while updating schema: Cash Position` was encountered when I first try to create the below measure:

`m["Ccy2"] = tt.agg.sum(flow_table["ccy2Amount"])`

However, re-running the measure again works.

![issue_500_create_measure](https://user-images.githubusercontent.com/35210495/150928936-ae8d1d4f-cc66-492c-8276-5cc4c8e4397a.gif)

Source: [fx_cashposition.zip](https://github.com/atoti/atoti/files/7931409/fx_cashposition.zip)

## Environment
- atoti: 0.6.4
- Python: 3.8.12
- Operating system: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/7931323/server.log)

<details><pre>
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
C:\Users\YEOHUI~1\AppData\Local\Temp/ipykernel_2876/3129460466.py in <module>
----> 1 m["Ccy2"] = tt.agg.sum(flow_table["ccy2Amount"])

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_runtime_type_checking_utils.py in typechecked_func_wrapper(*args, **kwargs)
    183 
    184             # Call the actual function.
--> 185             return self._func(*args, **kwargs)
    186 
    187         # Mark the function as typechecked and return it.

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\measures.py in __setitem__(self, key, value)
     92         value: MeasureLike,
     93     ) -> None:
---> 94         self.update({key: value})
     95 
     96     @overload

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_runtime_type_checking_utils.py in typechecked_func_wrapper(*args, **kwargs)
    183 
    184             # Call the actual function.
--> 185             return self._func(*args, **kwargs)
    186 
    187         # Mark the function as typechecked and return it.

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\measures.py in update(self, _Measures__m, **kwargs)
    126             other.update(__m)
    127         other.update(**kwargs)
--> 128         self._update(other)
    129 
    130     # Custom override types on purpose so that measure-like objects can be inserted.

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\measures.py in _update(self, other)
    149                 raise ValueError(f"Cannot create a measure from {measure}") from err
    150 
--> 151             self._java_api.publish_measures(self._cube_name)
    152 
    153     def __delitem__(self, key: str) -> None:

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     76                 else f"{java_api.get_throwable_root_cause(java_exception.java_exception)}"
     77             )
---> 78             raise AtotiJavaException(
     79                 cause,
     80                 java_traceback=str(java_exception),

AtotiJavaException: [500] Issue while updating schema: Cash Position
</pre></details>

**Comment by bloussou** [comment]
Same issue as https://support.activeviam.com/jira/browse/PIVOT-5022 :
Full stack trace :
```
AtotiJavaException: An error occurred while calling o1018.publishMeasures.
: com.qfs.fwk.services.InternalServiceException: [500] Issue while updating schema: Cash Position
	at com.qfs.fwk.services.ServiceException.create(ServiceException.java:97)
	at com.qfs.fwk.services.ServiceException.wrap(ServiceException.java:194)
	at com.activeviam.pivot.structure.action.impl.UpdatePivotManagerActionVisitor.visit(UpdatePivotManagerActionVisitor.java:56)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.activeviam.pivot.structure.impl.ManagerStructureUpdatePlan.accept(ManagerStructureUpdatePlan.java:45)
	at com.quartetfs.biz.pivot.impl.StructuralManagerTransaction.applyChanges(StructuralManagerTransaction.java:97)
	at com.quartetfs.biz.pivot.impl.StructuralManagerTransaction.lambda$new$0(StructuralManagerTransaction.java:54)
	at com.qfs.store.transaction.impl.StructuralSchemaTransaction.performCallbackAction(StructuralSchemaTransaction.java:172)
	at com.qfs.store.transaction.impl.StructuralSchemaTransaction.lambda$commit$1(StructuralSchemaTransaction.java:129)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.performSchemaUpdate(FlexibleTransactionManager.java:121)
	at com.qfs.store.transaction.impl.StructuralSchemaTransaction.commit(StructuralSchemaTransaction.java:129)
	at com.quartetfs.biz.pivot.impl.StructuralManagerTransaction.commit(StructuralManagerTransaction.java:68)
	at com.quartetfs.biz.pivot.IInternalActivePivotManager.updateStructure(IInternalActivePivotManager.java:36)
	at io.atoti.pivot.impl.CubeImpl.publishMeasures(CubeImpl.java:692)
	at io.atoti.impl.SimpleManager.publishMeasures(SimpleManager.java:273)
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.publishMeasures(OutsideTransactionDataApiImpl.java:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: This partitioning is not implied by SinglePartitioning {hash8(2147483647)}
	at com.qfs.store.part.impl.SinglePartitioning.getPartitionId(SinglePartitioning.java:207)
	at com.qfs.store.part.impl.SinglePartitioning$SinglePartitioningImpliedPartitionRetriever.visit(SinglePartitioning.java:432)
	at com.qfs.store.part.impl.SinglePartitioning$SinglePartitioningImpliedPartitionRetriever.visit(SinglePartitioning.java:407)
	at com.qfs.store.part.impl.SinglePartitioning.accept(SinglePartitioning.java:109)
	at com.qfs.store.part.impl.PartiallyKnownPartitioning.accept(PartiallyKnownPartitioning.java:168)
	at com.qfs.store.part.IPartitioning.getPartitionId(IPartitioning.java:101)
	at com.qfs.store.part.impl.PartiallyKnownPartitioning.getPartitionId(PartiallyKnownPartitioning.java:199)
	at com.qfs.store.part.impl.PartitioningUtil.initializePartitioning(PartitioningUtil.java:173)
	at com.qfs.pivot.cube.provider.partition.impl.APartitionedAggregateProviderBase.propagateAttributesToSpawned(APartitionedAggregateProviderBase.java:409)
	at com.qfs.pivot.cube.provider.jit.impl.JustInTimePartitionedAggregateProviderBase.spawnForNewCubeStructure(JustInTimePartitionedAggregateProviderBase.java:88)
	at com.qfs.pivot.cube.provider.jit.impl.MultiVersionPartitionedJustInTimeAggregateProvider.spawnForNewCubeStructure(MultiVersionPartitionedJustInTimeAggregateProvider.java:103)
	at com.quartetfs.biz.pivot.impl.ActivePivotBase.spawnAggregateProvider(ActivePivotBase.java:1432)
	at com.quartetfs.biz.pivot.impl.ActivePivotBase.spawnForNewStructure(ActivePivotBase.java:1482)
	at com.quartetfs.biz.pivot.impl.ActivePivotTransaction.newStructure(ActivePivotTransaction.java:209)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchema.updateStructure(ActivePivotSchema.java:333)
	at com.activeviam.pivot.structure.action.impl.UpdatePivotSchemaActionVisitor.visit(UpdatePivotSchemaActionVisitor.java:64)
	at com.activeviam.pivot.structure.action.impl.UpdateMeasuresAndProceduresAction.accept(UpdateMeasuresAndProceduresAction.java:27)
	at com.activeviam.pivot.structure.impl.PivotSchemaStructureUpdatePlan.lambda$accept$0(PivotSchemaStructureUpdatePlan.java:33)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.activeviam.pivot.structure.impl.PivotSchemaStructureUpdatePlan.accept(PivotSchemaStructureUpdatePlan.java:33)
	at com.activeviam.pivot.structure.action.impl.UpdatePivotManagerActionVisitor.visit(UpdatePivotManagerActionVisitor.java:53)
	... 25 more
```

**Comment by bloussou** [comment]
Closing this at it is solved in `0.6.5`
