### ISSUE TITLE
Measure was not found in cube - Formatting of measure

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#477]
## Steps to reproduce
I had the measure `m["Ghana Txn Amount"] = tt.agg.sum(ghana_trade_tbl["Ghana Txn Amount"])`. I tried to format it but I encountered the below exception:
![image](https://user-images.githubusercontent.com/35210495/155080745-15a2c79d-f866-4af6-8c28-8d56500fc168.png)

Source: [bishop.zip](https://github.com/atoti/atoti/files/8114430/bishop.zip)

## Environment

- atoti: 0.6.4
- Python: 3.8.12
- Operating system: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/8114352/server.log)

<details><pre>---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     70         try:
---> 71             return method(java_api, *args, **kwargs)
     72         except Py4JJavaError as java_exception:

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_java_api.py in publish_measures(self, cube_name)
    148         """Publish the new measures."""
--> 149         self._outside_transaction_api().publishMeasures(cube_name)
    150 

C:\Apps\miniconda3\envs\ds\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1308         answer = self.gateway_client.send_command(command)
-> 1309         return_value = get_return_value(
   1310             answer, self.gateway_client, self.target_id, self.name)

C:\Apps\miniconda3\envs\ds\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".

Py4JJavaError: An error occurred while calling o175.publishMeasures.
: com.qfs.fwk.services.NotFoundException: [404] Measure Ghana Txn Amount was not found in cube Trades
	at com.activeviam.pivot.structure.impl.WritablePivotStructure.lambda$updateMeasure$8(WritablePivotStructure.java:181)
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
	at com.activeviam.pivot.structure.impl.WritablePivotStructure.updateMeasure(WritablePivotStructure.java:175)
	at com.activeviam.pivot.structure.impl.ActivePivotManagerUpdater$MeasureUpdater.lambda$withFormatter$7(ActivePivotManagerUpdater.java:443)
	at com.activeviam.pivot.structure.impl.WritablePivotSchemaStructure.updatePivot(WritablePivotSchemaStructure.java:158)
	at com.activeviam.pivot.structure.impl.ActivePivotManagerUpdater$MeasureUpdater.withFormatter(ActivePivotManagerUpdater.java:441)
	at io.atoti.pivot.measure.MeasureManagerImpl.lambda$setMeasureFormatter$4(MeasureManagerImpl.java:425)
	at io.atoti.pivot.measure.MeasureManagerImpl$MeasureUpdate.apply(MeasureManagerImpl.java:465)
	at io.atoti.pivot.measure.MeasureManagerImpl.publishPendingMeasures(MeasureManagerImpl.java:410)
	at io.atoti.pivot.impl.CubeImpl.lambda$publishMeasures$9(CubeImpl.java:695)
	at com.quartetfs.biz.pivot.impl.StructuralManagerTransaction.update(StructuralManagerTransaction.java:62)
	at com.quartetfs.biz.pivot.IInternalActivePivotManager.updateStructure(IInternalActivePivotManager.java:36)
	at io.atoti.pivot.impl.CubeImpl.publishMeasures(CubeImpl.java:692)
	at io.atoti.impl.SimpleManager.publishMeasures(SimpleManager.java:273)
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.publishMeasures(OutsideTransactionDataApiImpl.java:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
C:\Users\YEOHUI~1\AppData\Local\Temp/ipykernel_10708/3254702402.py in <module>
----> 1 m["Ghana Txn Amount"].formatter = "DOUBLE[#,##0.000000]"

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\measure.py in formatter(self, value)
    191             cube_name=self._cube_name, measure_name=self.name, formatter=value
    192         )
--> 193         self._java_api.publish_measures(self._cube_name)
    194 
    195     @property

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     73             cause = (
     74                 str(java_exception)
---> 75                 if get_env_flag(_ATOTI_VERBOSE_JAVA_EXCEPTIONS)
     76                 else f"{java_api.get_throwable_root_cause(java_exception.java_exception)}"
     77             )

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_os_utils.py in get_env_flag(variable_name)
      5 
      6 def get_env_flag(variable_name: str) -> bool:
----> 7     return str_to_bool(
      8         os.environ.get(
      9             variable_name,

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti_core\str_to_bool.py in str_to_bool(value)
     14         return False
     15 
---> 16     raise ValueError(
     17         f"Expected one of {_TRUE_VALUES} or {_FALSE_VALUES} but received {value}."
     18     )

ValueError: Expected one of ('true', '1') or ('false', '0') but received atotijavaexception.</pre></details>

**Comment by Acriss** [comment]
Hi Huifang,

I unfortunately cannot install the dependency openpyxl, so I can't test your notebook.
However, I'm quite confident that this is the same issue as activeviam/atoti#3099 and that it will be resolved with the 0.6.5 release.
This seems to be one of these Partial References issues we stumble upon when some keys of the joined store (the one that holds your measure Ghana Txn ...) are not mapped to a field of the base store.

Cheers,
Acris
