### ISSUE TITLE
Unclear error when adding simulation record of the wrong type

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#51]
## Steps to reproduce

```python
import pandas as pd

dummy = {
    "ProductId": [0, 1, 2, 3],
    "Class": ["Driver", "Driver", "Complementary", "Independent"],
    "SellingPrice": [10.0, 8.0, 5.0, 12.0],
}
dummy_df = pd.DataFrame(data=dummy)

import atoti

session = atoti.create_session()
dummy_store = session.read_pandas(dummy_df, store_name="dummy", keys=["ProductId"])
cube = session.create_cube(dummy_store)

m = cube.measures
lvl = cube.levels

simulation = cube.setup_simulation(
    "DUMMY_SIMU",
    levels=[lvl["Class"], lvl["ProductId"]],
    multiply=[m["SellingPrice.SUM"]],
)

test = simulation.scenarios["test"]
test += ("Complementary", "*", 5)
```

## Actual Result

Putting aside the double stack trace (cf #43 ), the main error message is `java.lang.StringIndexOutOfBoundsException: String index out of range: -1`

```
Traceback (most recent call last):
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/exceptions.py", line 215, in catch_py4j_exceptions
    return method(*args, **kwargs)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/_java_api.py", line 778, in insert_multiple_on_store_scenario
    self.java_api.insertMultipleOnStoreBranch(
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/vendor/atotipy4j/java_gateway.py", line 1313, in __call__
    return_value = get_return_value(
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/vendor/atotipy4j/protocol.py", line 322, in get_return_value
    raise Py4JJavaError(
Py4JJavaError: An error occurred while calling o2.insertMultipleOnStoreBranch.
: com.qfs.fwk.services.BadArgumentException: [400] Invalid records to add
	at com.qfs.store.service.impl.DatastoreService.parseRows(DatastoreService.java:1112)
	at com.qfs.store.service.impl.DatastoreService.doInsertTransaction(DatastoreService.java:913)
	at com.qfs.store.service.impl.DatastoreService.doDatastoreAction(DatastoreService.java:877)
	at com.qfs.store.service.impl.DatastoreService.lambda$editDatastore$4(DatastoreService.java:827)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2500)
	at com.qfs.store.service.impl.DatastoreService.editDatastore(DatastoreService.java:821)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.lambda$editDatastore$0(RegisteringChouketDatastoreService.java:82)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService$DatastoreServiceOperation.initialLoad(RegisteringChouketDatastoreService.java:141)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.registerOperation(SimpleActiveViamSession.java:552)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.registerOperation(RegisteringChouketDatastoreService.java:113)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.editDatastore(RegisteringChouketDatastoreService.java:81)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.performJsonDatastoreActions(StoreOnBranchImpl.java:212)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.performJsonDatastoreAction(StoreOnBranchImpl.java:202)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.insertRows(StoreOnBranchImpl.java:103)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.insertRows(StoreOnBranchImpl.java:123)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.insertMultipleOnStoreBranch(ActiveViamSessionApiImpl.java:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:368)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:392)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:424)
	at com.quartetfs.fwk.format.impl.LongParser.parse(LongParser.java:30)
	at com.quartetfs.fwk.format.impl.LongParser.parse(LongParser.java:23)
	at com.qfs.store.service.impl.DatastoreService.parseRows(DatastoreService.java:1103)
	... 28 more


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-5-a4c563ff8295>", line 1, in <module>
    test += ("Complementary", "*", 5)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/_docs_utils.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/simulation.py", line 416, in __iadd__
    self.append(row)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/_docs_utils.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/simulation.py", line 410, in append
    self._java_api.insert_multiple_on_store_scenario(
  File "/home/jbe/.conda/envs/atoti-latest/lib/python3.8/site-packages/atoti/exceptions.py", line 217, in catch_py4j_exceptions
    raise AtotiJavaException(
AtotiJavaException: An error occurred in the JVM:
An error occurred while calling o2.insertMultipleOnStoreBranch.
: com.qfs.fwk.services.BadArgumentException: [400] Invalid records to add
	at com.qfs.store.service.impl.DatastoreService.parseRows(DatastoreService.java:1112)
	at com.qfs.store.service.impl.DatastoreService.doInsertTransaction(DatastoreService.java:913)
	at com.qfs.store.service.impl.DatastoreService.doDatastoreAction(DatastoreService.java:877)
	at com.qfs.store.service.impl.DatastoreService.lambda$editDatastore$4(DatastoreService.java:827)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2500)
	at com.qfs.store.service.impl.DatastoreService.editDatastore(DatastoreService.java:821)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.lambda$editDatastore$0(RegisteringChouketDatastoreService.java:82)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService$DatastoreServiceOperation.initialLoad(RegisteringChouketDatastoreService.java:141)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.registerOperation(SimpleActiveViamSession.java:552)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.registerOperation(RegisteringChouketDatastoreService.java:113)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.editDatastore(RegisteringChouketDatastoreService.java:81)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.performJsonDatastoreActions(StoreOnBranchImpl.java:212)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.performJsonDatastoreAction(StoreOnBranchImpl.java:202)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.insertRows(StoreOnBranchImpl.java:103)
	at com.activeviam.chouket.edit.impl.StoreOnBranchImpl.insertRows(StoreOnBranchImpl.java:123)
	at com.activeviam.chouket.api.impl.ActiveViamSessionApiImpl.insertMultipleOnStoreBranch(ActiveViamSessionApiImpl.java:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:368)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:392)
	at javolution.text.TypeFormat.parseLong(TypeFormat.java:424)
	at com.quartetfs.fwk.format.impl.LongParser.parse(LongParser.java:30)
	at com.quartetfs.fwk.format.impl.LongParser.parse(LongParser.java:23)
	at com.qfs.store.service.impl.DatastoreService.parseRows(DatastoreService.java:1103)
	... 28 more
```

## Expected Result

It took me a while to understand what the issue was:
- `"*"` has been moved to `None` cf https://github.com/atoti/atoti/issues/50
- the issue is a type issue: i.e. the simulated level is of type `double` but receives a string `"*"`

I would therefore expect a clearer message such as `Invalid type string for level ProductId: received * but expected a double`

## Environment

- Atoti: 0.4.0.20200520133308
- Python: 3.8.2
- Operating System: linux

**Comment by fabiencelier** [comment]
The issue has been resolved by  activeviam/activepivot#2504 and the current message is
<pre>
 Parsing error when inserting value "*" in field "ProductId" of type "long"
</pre>
