### ISSUE TITLE
Error using BasicAuthentication

### ISSUE THREAD

**Issue by sjmg** [atoti/atoti#528]
Hello,

We are trying to connect wit ActivePivot cube to extract information from MDX.

 

In previous version, we use the deprecated method "create_basic_authentication". But in the actual version 0.6.4 we are not able to connect.

This is our  code:

 

import atoti as tt
print("Version: " + tt._version_)
admin_auth = tt.query.BasicAuthentication(username='admin',pasword='admin')

 

and we receibe this response:
![image](https://user-images.githubusercontent.com/67267890/159475625-4b0190de-a11c-4992-9ae1-5fe567b32361.png)

We don't understand where is the error, could you help us?

 

Thanks so much

 

Regards

**Comment by tibdex** [comment]
The error message in better in Python 3.10:

```bash
❯ python                                                                                                                                                                                                                             (tryito) 
Python 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:58:48) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import atoti as tt
>>> tt.__version__
'0.6.4'
>>> tt.query.BasicAuthentication(username='admin',pasword='admin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tibdex/miniconda3/envs/tryito/lib/python3.10/site-packages/atoti_core/keyword_only_dataclass.py", line 27, in init_enforcing_keyword_only_arguments
    init(self, **kwargs)
TypeError: BasicAuthentication.__init__() got an unexpected keyword argument 'pasword'
```

**Comment by sjmg** [comment]
Hello,

first of all, thanks so much for your answer

I changed and have the same problem

![image](https://user-images.githubusercontent.com/67267890/159509894-682564ff-cd3f-44c4-b70a-6d1d837427f2.png)


Do you have any other idea?

Thanks so much

**Comment by bloussou** [comment]
Which version of python are you using ? Is it `3.9.7` ? (it has a known issue)

**Comment by sjmg** [comment]
yes, it's version 3.9.7

**Comment by bloussou** [comment]
Then it is a python bug https://bugs.python.org/issue44806 . You have to change your python version to avoid this issue, in the next version of atoti we will require a python version different than this broken one
