### ISSUE TITLE
Encoding error from read_csv is not thrown in notebook

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#552]
## Steps to reproduce

I have the following CSV: [live_results.csv](https://github.com/atoti/atoti/files/8470079/live_results.csv).
I was able to load the csv successfully without the encoding. However, the table results nothing.

```
results_tbl = session.read_csv(
    "live_results.csv",
    table_name="results",
    keys=["Candidate name", "Result date"],
    # encoding="iso-8859-15",
)

```
Although no error was shown on the notebook, the below error can be found in the log:
```
2022-04-12 14:14:51.649 ERROR 12860 --- [csv-worker-CSVSource-2] com.qfs.msg.impl.LogMessageHandler       : message FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks-upgrade\notebooks\french-presidential-election\data\2022\live_results.csv, lastModifiedTime=Tue Apr 12 11:51:43 SGT 2022] failed

java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source) ~[na:na]
	at com.qfs.msg.csv.impl.ParserTask.decode(ParserTask.java:375) ~[atoti-aws.jar:na]
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:217) ~[atoti-aws.jar:na]
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:42) ~[atoti-aws.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	at com.qfs.msg.csv.impl.ParserThread.run(ParserThread.java:64) ~[atoti-aws.jar:na]
```
We should have the standard message that records are not loaded into the table so that we can check out the table's `LoadingReport`.

## Environment

- atoti: 0.6.5
- Python: 3.9.12
- Operating system: win32

**Comment by HuifangYeo** [comment]
Sample notebook: [encoding_notebook.zip](https://github.com/atoti/atoti/files/8470128/encoding_notebook.zip)
