### ISSUE TITLE
Custom filter comparing member to measures: incompatible types

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#562]
## Steps to reproduce
The measure `m["Winning candidate"]` is of string type since it's computed using `max_member`.  
I would like to filter on the candidates where their name fits the `Winning candidate` but I encounter the error `Incompatible types. Cannot compare class java.lang.Long with class java.lang.String`.

![image](https://user-images.githubusercontent.com/35210495/163324685-aaa0811c-7496-4ad8-b2f7-23ddab1bdfa0.png)

## Environment

- atoti: 0.6.5
- Python: 3.9.12
- Operating system: win32

## Logs (if relevant)

<details><pre>
2022-04-14 14:09:29.024  WARN 37036 --- [activepivot-health-event-dispatcher] c.a.h.m.ILoggingHealthEventHandler       : [activepivot, query] WARNING 2022-04-14T06:09:29.022Z uptime=10330641ms com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.report:1582 thread=qfs-common-worker-49 thread_id=269 event_type=ActivePivotQueryFailed user=anonymousUser roles=[ROLE_USER, ROLE_ADMIN] query=ActivePivotSyncActionQuery execution_time=14ms exception=com.quartetfs.fwk.query.QueryException: ActivePivotSyncActionQuery: action=MdxActionWithResult (mdx=SELECT   NON EMPTY {[Measures].[Winning candidates], [Measures].[Winning votes]} DIMENSION PROPERTIES ANCESTOR_CAPTION ON COLUMNS,   NON EMPTY Hierarchize(Descendants({[results].[Region].[AllMember]}, 1, SELF_AND_BEFORE)) DIMENSION PROPERTIES ANCESTOR_CAPTION ON ROWS  FROM (SELECT  Filter([Candidate_mapping].[Candidate name].[Candidate name].Members, [Measures].[contributors.COUNT] = [Measures].[Winning candidates]) ON COLUMNS  FROM [election])  CELL PROPERTIES VALUE,FORMATTED_VALUE,BACK_COLOR,FORE_COLOR,FONT_FLAGS), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@32992944

com.quartetfs.fwk.query.QueryException: ActivePivotSyncActionQuery: action=MdxActionWithResult (mdx=SELECT   NON EMPTY {[Measures].[Winning candidates], [Measures].[Winning votes]} DIMENSION PROPERTIES ANCESTOR_CAPTION ON COLUMNS,   NON EMPTY Hierarchize(Descendants({[results].[Region].[AllMember]}, 1, SELF_AND_BEFORE)) DIMENSION PROPERTIES ANCESTOR_CAPTION ON ROWS  FROM (SELECT  Filter([Candidate_mapping].[Candidate name].[Candidate name].Members, [Measures].[contributors.COUNT] = [Measures].[Winning candidates]) ON COLUMNS  FROM [election])  CELL PROPERTIES VALUE,FORMATTED_VALUE,BACK_COLOR,FORE_COLOR,FONT_FLAGS), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@32992944
	at com.quartetfs.biz.pivot.query.impl.ActivePivotSyncActionAttachedQuery.executeAsync(ActivePivotSyncActionAttachedQuery.java:58) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.biz.pivot.impl.AActivePivotQueryExecutor.executeAsync(AActivePivotQueryExecutor.java:31) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion.executeAttachedAsync(ActivePivotVersion.java:1117) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.computeSafely(ActivePivotVersion.java:1363) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.execSafely(CancellableCountedCompleter.java:163) ~[atoti-aws.jar:na]
	at com.quartetfs.biz.pivot.context.impl.ContextualCancellableCountedCompleter.execSafely(ContextualCancellableCountedCompleter.java:117) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:190) ~[atoti-aws.jar:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
Caused by: com.quartetfs.pivot.mdx.MdxException: SELECT   NON EMPTY {[Measures].[Winning candidates], [Measures].[Winning votes]} DIMENSION PROPERTIES ANCESTOR_CAPTION ON COLUMNS,   NON EMPTY Hierarchize(Descendants({[results].[Region].[AllMember]}, 1, SELF_AND_BEFORE)) DIMENSION PROPERTIES ANCESTOR_CAPTION ON ROWS  FROM (SELECT  Filter([Candidate_mapping].[Candidate name].[Candidate name].Members, [Measures].[contributors.COUNT] = [Measures].[Winning candidates]) ON COLUMNS  FROM [election])  CELL PROPERTIES VALUE,FORMATTED_VALUE,BACK_COLOR,FORE_COLOR,FONT_FLAGS
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.planEvaluate(ASelectStatementExecutor.java:282) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.noSyncExecuteAfterParse(ASelectStatementExecutor.java:483) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor$MdxActionWithResult.execute(ASelectStatementExecutor.java:607) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor$MdxActionWithResult.execute(ASelectStatementExecutor.java:582) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.biz.pivot.query.impl.ActivePivotSyncUtils$AAction.execute(ActivePivotSyncUtils.java:204) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.biz.pivot.query.impl.ActivePivotSyncActionAttachedQuery.executeAsync(ActivePivotSyncActionAttachedQuery.java:56) ~[activepivot-impl-5.11.2-20220322.jar!/:na]
	... 12 common frames omitted
Caused by: com.activeviam.fwk.ActiveViamRuntimeException: com.quartetfs.pivot.mdx.MdxException: Incompatible types. Cannot compare class java.lang.Long with class java.lang.String
	at com.quartetfs.pivot.mdx.func.impl.BooleanFilter.check(BooleanFilter.java:53) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.SetBuilder.add(SetBuilder.java:116) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.SetBuilder.execute(SetBuilder.java:102) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.SetBuilder.execute(SetBuilder.java:35) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.ARandomAccessSet.forEachTuple(ARandomAccessSet.java:60) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.ARandomAccessSet.forEachTuple(ARandomAccessSet.java:33) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.Sets$ExpandedSet.forEachTuple(Sets.java:1450) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.eval.set.impl.SetBuilder.addAll(SetBuilder.java:92) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.impl.FilterFunction$FilterFunctionDefinition.evaluate(FilterFunction.java:100) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.impl.FilterFunction$FilterFunctionDefinition.evaluate(FilterFunction.java:78) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator$EvaluateVisitor.contextVisit(ExpressionEvaluator.java:417) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.AContextVisitor.visit(AContextVisitor.java:77) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.base.impl.FunctionCall.accept(FunctionCall.java:70) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator.evaluateType(ExpressionEvaluator.java:300) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator.evaluateSet(ExpressionEvaluator.java:216) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectBaseEvaluator.executeAxis(ASelectBaseEvaluator.java:54) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectBaseEvaluator.executeAxis(ASelectBaseEvaluator.java:26) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStepExecutor.handleSelect(ASelectStepExecutor.java:105) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStepExecutor.runStep(ASelectStepExecutor.java:45) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.plan.impl.PassExecutor.process(PassExecutor.java:62) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.realtime.impl.ADepthFirstVisitor.visitSubSelect(ADepthFirstVisitor.java:64) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.plan.impl.APassVisitor.visit(APassVisitor.java:73) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.plan.impl.APassVisitor.visit(APassVisitor.java:28) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.utils.impl.ColoredDirectedAcyclicGraph.accept(ColoredDirectedAcyclicGraph.java:119) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.RecursiveSelectPlanuator.handleSubSelect(RecursiveSelectPlanuator.java:131) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ARecursiveSelectVisitor.visit(ARecursiveSelectVisitor.java:37) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ARecursiveSelectVisitor.visit(ARecursiveSelectVisitor.java:52) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.RecursiveSelectPlanuator.visit(RecursiveSelectPlanuator.java:71) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.doPlanEvaluate(ASelectStatementExecutor.java:345) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.planEvaluate(ASelectStatementExecutor.java:276) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	... 17 common frames omitted
Caused by: com.quartetfs.pivot.mdx.MdxException: Incompatible types. Cannot compare class java.lang.Long with class java.lang.String
	at com.quartetfs.pivot.mdx.func.impl.ComparisonFunctions$EQFunction.compare(ComparisonFunctions.java:78) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.impl.ComparisonFunctions$ComparisonFunction.evaluate(ComparisonFunctions.java:430) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.impl.ComparisonFunctions$EQFunction.evaluate(ComparisonFunctions.java:42) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.base.impl.AFixedFunction$FixedFunctionSingleDefinition.evaluate(AFixedFunction.java:197) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator$EvaluateVisitor.contextVisit(ExpressionEvaluator.java:417) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.AContextVisitor.visit(AContextVisitor.java:77) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.base.impl.FunctionCall.accept(FunctionCall.java:70) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator.evaluateScalar(ExpressionEvaluator.java:176) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator.evaluateType(ExpressionEvaluator.java:298) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.impl.ExpressionEvaluator.evaluateBoolean(ExpressionEvaluator.java:181) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	at com.quartetfs.pivot.mdx.func.impl.BooleanFilter.check(BooleanFilter.java:50) ~[activepivot-mdx-impl-5.11.2-20220322.jar!/:na]
	... 46 common frames omitted
</pre></details>

**Comment by bloussou** [comment]
Hello,
This is not a bug. `contributors.COUNT` is of type long and the measure define with `max_member()` is of type `String` since it is returning the candidate name with the highest `contributors.COUNT`.
Two solutions :
- an advanced filters with `contributors.COUNT` **is the highest** with 1 value
![image](https://user-images.githubusercontent.com/32448554/165263497-3c3bfb16-d0cf-4409-85e2-56abd94fe06d.png)
- Create another measure using [`max()`](https://docs.atoti.io/latest/lib/atoti/atoti.agg.max.html#atoti.agg.max) and use it in your mdx expression

**Comment by HuifangYeo** [comment]
Sorry, my bad.
