### ISSUE TITLE
Error when loading data on joined table simulation if table has no keys

### ISSUE THREAD

**Issue by bloussou** [atoti/atoti#565]
### Discussed in https://github.com/atoti/atoti/discussions/564

<div type='discussions-op-text'>

<sup>Originally posted by **agent3133** April 15, 2022</sup>
Hi,

is it possible to use a dimension table to perform a source simulation?

If I execute the code below, I get an AtotiJavaException:
```
AtotiJavaException: An error occurred while calling o98.endTransaction.
: com.activeviam.fwk.ActiveViamRuntimeException: Transaction commit failed
	at com.qfs.store.transaction.ITransactionExceptionHandler.onCommitFailure(ITransactionExceptionHandler.java:45)
	at com.qfs.store.transaction.impl.TransactionPerformer.close(TransactionPerformer.java:136)
	at com.qfs.store.transaction.impl.TransactionPerformer.commitTransaction(TransactionPerformer.java:163)
	at io.atoti.api.impl.DataApiImpl.commitTransaction(DataApiImpl.java:84)
	at io.atoti.api.impl.DataApiImpl.endTransaction(DataApiImpl.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.qfs.store.transaction.DatastoreTransactionException: An exception occurred during the preparation of the commit of the transaction: DatastoreSchemaTransactionInformation{id=1, epoch=null, writableStoreIds=[0, 1], lockedStoresIds=[0, 1], transactionStatistics=null, branch=New Scenario, shadow=false}
	at com.qfs.store.transaction.impl.TransactionManager.doPrepareCommit(TransactionManager.java:1112)
	at com.qfs.store.transaction.impl.TransactionManager.commitTransaction(TransactionManager.java:1203)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.commitTransaction(FlexibleTransactionManager.java:481)
	at com.qfs.store.transaction.impl.TransactionPerformer.close(TransactionPerformer.java:134)
	... 15 more
Caused by: com.qfs.fwk.services.InternalServiceException: [500] com.qfs.fwk.services.InternalServiceException: [500] Failed to process update of type MergingStorePartitionUpdate for partition 0 of store `Scenario_Table`. Failed operation summary: added: 0, deleted: 0, updated: 0
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at com.qfs.store.impl.DatastoreSchemaBase.doForEachStore(DatastoreSchemaBase.java:353)
	at com.qfs.store.impl.DatastoreSchemaBase.flushStoresTransactions(DatastoreSchemaBase.java:389)
	at com.qfs.store.impl.DatastoreSchemaBase.prepareCommit(DatastoreSchemaBase.java:322)
	at com.qfs.store.impl.MultiVersionDatastoreSchema.prepareCommit(MultiVersionDatastoreSchema.java:459)
	at com.qfs.store.transaction.impl.DatastoreSchemaTransactionManager.prepareCommitTransaction(DatastoreSchemaTransactionManager.java:207)
	at com.qfs.store.transaction.impl.TransactionManager.doPrepareCommit(TransactionManager.java:1107)
	... 18 more
Caused by: com.qfs.fwk.services.InternalServiceException: [500] Failed to process update of type MergingStorePartitionUpdate for partition 0 of store `Scenario_Table`. Failed operation summary: added: 0, deleted: 0, updated: 0
	at com.qfs.store.impl.StorePartitionWorker$RunConsumer.process(StorePartitionWorker.java:460)
	at com.qfs.store.impl.StorePartitionWorkUnitQueue.consume(StorePartitionWorkUnitQueue.java:200)
	at com.qfs.store.impl.StorePartitionWorker$ProcessingTask.processPendingUnits(StorePartitionWorker.java:403)
	at com.qfs.store.impl.StorePartitionWorker$ProcessingTask.compute(StorePartitionWorker.java:373)
	at java.base/java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.qfs.store.record.KeyConstraintViolationException: Record [1, 1](RecordView[2, 1]) could not be inserted into partition 0 of store Scenario_Table, it has the same unique index as record [1, 1000](ColumnarRecordSetReader[2, 1000]) because the reference Scenario Example_to_Scenario_Table enforces that records with different primary keys (fields:[], values: []) must have different values on the following fields: [TradeId], values: [1]
	at com.qfs.store.impl.StorePartitionTransaction.addRecordFieldIndexesAndReferences(StorePartitionTransaction.java:592)
	at com.qfs.store.impl.StorePartitionTransaction.doAddRecord(StorePartitionTransaction.java:524)
	at com.qfs.store.impl.StorePartitionTransaction.unsafeAddRecord(StorePartitionTransaction.java:405)
	at com.qfs.store.impl.StorePartitionTransaction.addRecord(StorePartitionTransaction.java:358)
	at com.qfs.store.impl.StorePartitionRecordAddUnit.run(StorePartitionRecordAddUnit.java:36)
	at com.qfs.store.impl.StorePartitionWorker$RunConsumer.process(StorePartitionWorker.java:458)
	... 9 more
```

```python
import atoti as tt
import pandas as pd 

session = tt.Session()
session.link()
df = pd.DataFrame({"TradeId":["1","2","3"], 
                   "Cashflows":[100, 200, 300], 
                   "Customer": ["Homer", "Bart", "Marge"]}
                   )
main_table = session.read_pandas(df, table_name="Scenario Example")

table_with_scenario = session.read_pandas(
    pd.DataFrame(
        {"TradeId":["1","2","3"],
        "Items":[1000,2000,3000]}
    ),
    table_name='Scenario_Table'
)

main_table.join(table_with_scenario, mapping={"TradeId":"TradeId"})

cube = session.create_cube(main_table)

table_with_scenario.scenarios["New Scenario"].load_pandas(
        pd.DataFrame(
        {"TradeId":["1","2","3"],
        "Items":[1,2,3]}
        )
    )
```

Best Regards,
Alex</div>

**Comment by bloussou** [comment]
I'm closing this because I think it is an issue in the data model. `TradeId` must be a key of the base store and probably of the `ScenarioTable` too
