### ISSUE TITLE
_DATAMEMBER_ on multilevel hierarchy block the session.

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#629]
## Steps to reproduce

```python
import atoti as tt
session = tt.Session()
table_1 = session.create_table("table_1", types={"l1": tt.type.STRING, "l2": tt.type.STRING, "l3": tt.type.STRING})
table_1.append(("l1","_DATAMEMBER_","l3"))
cube=session.create_cube(table_1)
cube.hierarchies["test"] = [cube.levels["l1"], cube.levels["l2"], cube.levels["l3"]]
```

## Actual Result
```
AtotiJavaException                        Traceback (most recent call last)
Input In [8], in <cell line: 6>()
      4 table_1.append(("l1","_DATAMEMBER_","l3"))
      5 cube=session.create_cube(table_1)
----> 6 cube.hierarchies["test"] = [cube.levels["l1"], cube.levels["l2"], cube.levels["l3"]]

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\_runtime_type_checking_utils.py:179, in _TypecheckWrapperFactory.create_wrapper.<locals>.typechecked_func_wrapper(*args, **kwargs)
    176 typeguard.check_argument_types(memo)
    178 # Call the actual function.
--> 179 return self._func(*args, **kwargs)

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\typeguard\__init__.py:1015, in typechecked.<locals>.wrapper(*args, **kwargs)
   1013 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
   1014 check_argument_types(memo)
-> 1015 retval = func(*args, **kwargs)
   1016 try:
   1017     check_return_type(retval, memo)

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\hierarchies.py:102, in Hierarchies.__setitem__(self, key, value)
     96 @typechecked
     97 def __setitem__(  # type: ignore
     98     self,
     99     key: HierarchyKey,
    100     value: _HierarchyDescription,
    101 ) -> None:
--> 102     self.update({key: value})

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\_runtime_type_checking_utils.py:179, in _TypecheckWrapperFactory.create_wrapper.<locals>.typechecked_func_wrapper(*args, **kwargs)
    176 typeguard.check_argument_types(memo)
    178 # Call the actual function.
--> 179 return self._func(*args, **kwargs)

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\hierarchies.py:163, in Hierarchies.update(self, _Hierarchies__m, **kwargs)
    158 other.update(**kwargs)
    159 final_hierarchies: Mapping[HierarchyKey, Mapping[str, LevelOrColumn]] = {
    160     hierarchy_key: _normalize_levels(levels_or_columns)
    161     for hierarchy_key, levels_or_columns in other.items()
    162 }
--> 163 self._update(final_hierarchies)

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\hierarchies.py:120, in Hierarchies._update(self, other)
    116     structure[dimension_name].update(
    117         {hierarchy_name: _get_hierarchy_levels(levels_or_columns)}
    118     )
    119 self._java_api.update_hierarchies_for_cube(self._cube_name, structure=structure)
--> 120 self._java_api.refresh()

File ~\miniconda3\envs\atoti-plus-0.6.6\lib\site-packages\atoti\_java_api.py:142, in _enhance_py4j_errors.<locals>.wrapped_method(self, *args, **kwargs)
    136 except Py4JJavaError as java_exception:
    137     cause = (
    138         str(java_exception)
    139         if get_env_flag(_ATOTI_VERBOSE_JAVA_EXCEPTIONS)
    140         else self.get_throwable_root_cause(java_exception.java_exception)
    141     )
--> 142     raise AtotiJavaException(
    143         cause,
    144         java_traceback=str(java_exception),
    145         java_exception=java_exception,
    146     ) from None

AtotiJavaException: State transition INIT => STARTED failed because of an internal exception.
```

## Environment

- atoti: 0.6.6
- Python: 3.10.4
- Operating system: win32

**Comment by tibdex** [comment]
When setting `os.environ["ATOTI_VERBOSE_JAVA_EXCEPTIONS"] = True` and rearranging the lines to:

```python
import atoti as tt
session = tt.Session()
table_1 = session.create_table("table_1", types={"l1": tt.type.STRING, "l2": tt.type.STRING, "l3": tt.type.STRING})
cube=session.create_cube(table_1)
cube.hierarchies["test"] = [cube.levels["l1"], cube.levels["l2"], cube.levels["l3"]]

# Loading the data when the data model is fully defined
table_1.append(("l1","_DATAMEMBER_","l3"))
```

We have this exception:

```
AtotiJavaException: An error occurred while calling o87.endTransaction.
: com.activeviam.fwk.ActiveViamRuntimeException: Cannot deal with exception from ActivePivot schema table_1. Rollback is mandatory
	at com.activeviam.pivot.contribution.impl.DatastoreDataContributor.onSelfFailure(DatastoreDataContributor.java:126)
	at com.activeviam.store.impl.AdaptingFactOnlyListener.onSelfFailure(AdaptingFactOnlyListener.java:173)
	at com.qfs.store.selection.IDelegateCompositeSelectionListener.onSelfFailure(IDelegateCompositeSelectionListener.java:25)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.onListenerException(AsyncContinuousCompositeSelection.java:1510)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.transactionCommitted(AsyncContinuousCompositeSelection.java:1013)
	at com.qfs.store.impl.MultiVersionDatastoreSchema.fireTransactionCommitted(MultiVersionDatastoreSchema.java:395)
	at com.qfs.store.transaction.impl.DatastoreSchemaTransactionManager.fireTransactionCommitted(DatastoreSchemaTransactionManager.java:447)
	at com.qfs.store.transaction.impl.TransactionManager.commitTransaction(TransactionManager.java:1228)
	at com.qfs.store.transaction.impl.AlterableTransactionManager.commitTransaction(AlterableTransactionManager.java:491)
	at com.qfs.store.transaction.impl.TransactionPerformer.close(TransactionPerformer.java:134)
	at com.qfs.store.transaction.impl.TransactionPerformer.commitTransaction(TransactionPerformer.java:163)
	at io.atoti.api.impl.DataApiImpl.commitTransaction(DataApiImpl.java:85)
	at io.atoti.api.impl.DataApiImpl.endTransaction(DataApiImpl.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Cannot commit transaction from version 7
	at com.activeviam.pivot.contribution.impl.ADataContributorHandlingCubeTransaction.commitCubeTransaction(ADataContributorHandlingCubeTransaction.java:70)
	at com.activeviam.pivot.contribution.impl.DatastoreDataContributor.transactionCommitted(DatastoreDataContributor.java:112)
	at com.activeviam.store.impl.AdaptingFactOnlyListener.transactionCommitted(AdaptingFactOnlyListener.java:81)
	at com.qfs.store.selection.impl.DelegateCompositeSelectionListener.transactionCommitted(DelegateCompositeSelectionListener.java:64)
	at com.qfs.store.selection.impl.AsyncContinuousCompositeSelection.transactionCommitted(AsyncContinuousCompositeSelection.java:1011)
	... 20 more
```

which looks like an ActivePivot issue.

**Comment by tibdex** [comment]
[Internal ticket](https://support.activeviam.com/jira/browse/PIVOT-5619).

**Comment by Acriss** [comment]
Answered on internal ticket.

**Comment by tibdex** [comment]
Alexis, based on Pierre's answer on the internal ticket, do you agree that we can close this?
