### ISSUE TITLE
Rows with incorrect field type are excluded without feedback

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#64]
## Description

When the requested field type does not match the actual field type, parsing errors are currently silenced and rows are being excluded. We only discover about "missing facts" when making queries.

Furthermore, it seems the sampling occurs before parsing, so you may end up with nearly no rows loaded if out of the first 10000 rows most of them have a parsing error.

## Example A

```python
import pandas as pd

main_df = pd.DataFrame(
    data={
        "value": [1, 2, 1, "\\N", 2, 3, 4, "\\N"],
        "class": ["A", "A", "B", "C", "C", "C", "C", "C"],
    }
)

import atoti

session = atoti.create_session()

main_store = session.read_pandas(
    main_df, store_name="main", types={"value": atoti.types.INT}
)
```

This will load 6 facts out of 8 without any warnings. You can only realize that by checking the number of facts loaded (assuming you know what the total count should be) or by looking at the logs:

```
com.activeviam.fwk.ActiveViamRuntimeException: Exception while translating column value with parser Plugin Value (key=int, class com.quartetfs.fwk.format.impl.IntParser) in file FileSystemFileInfo [fullName=/tmp/atoti-mh_agyjh/main1y2qjt95.pdcvs, lastModifiedTime=Mon Jun 15 13:55:44 CEST 2020]. Parsed text was "\N"
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:169)
	at com.qfs.msg.impl.ColumnCalculationContext.processColumn(ColumnCalculationContext.java:159)
	at com.qfs.msg.impl.ColumnCalculationContext.process(ColumnCalculationContext.java:113)
	at com.qfs.msg.impl.ColumnCalculationContext.processTuple(ColumnCalculationContext.java:82)
	at com.qfs.msg.csv.translator.impl.AColumnarTranslator.translateTuple(AColumnarTranslator.java:125)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:26)
	at com.qfs.msg.csv.translator.impl.TupleTranslator.translate(TupleTranslator.java:19)
	at com.qfs.source.impl.TupleMessageChunk.append(TupleMessageChunk.java:45)
	at com.qfs.msg.csv.impl.Parser.parse(Parser.java:181)
	at com.qfs.msg.csv.impl.ParserTask.parseIteration(ParserTask.java:353)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:229)
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.qfs.msg.csv.impl.ParserThread.run(ParserThread.java:64)
Caused by: java.lang.NumberFormatException: Invalid integer representation for \N
	at javolution.text.TypeFormat.parseInt(TypeFormat.java:274)
	at javolution.text.TypeFormat.parseInt(TypeFormat.java:297)
	at javolution.text.TypeFormat.parseInt(TypeFormat.java:329)
	at com.quartetfs.fwk.format.impl.IntParser.parse(IntParser.java:30)
	at com.quartetfs.fwk.format.impl.IntParser.parse(IntParser.java:23)
	at com.qfs.msg.csv.impl.CSVColumnParser.compute(CSVColumnParser.java:161)
	... 16 more
```

## Example B

```python
import pandas as pd

main_df = pd.DataFrame(
    data={
        "value": np.full(8000, "\\N").tolist() + np.full(12000, 1).tolist(),
        "class": np.full(20000, "A"),
    }
)

import atoti

session = atoti.create_session()

main_store = session.read_pandas(
    main_df, store_name="main", types={"value": atoti.types.INT}
)
```

This will load 2000 rows and not 10000.

## Expected results

(1) I would expect at least to know about it. A little summary about the loaded rows like `Loaded 6 out of 8 rows.` or `Excluded 2 rows for incorrect 'value' type` would help, similar to what is in the log:
```
INFO: CSVSource: Processing of workload #0 completed in 76ms. 46 bytes (46) parsed into 9 lines (6 records published). Average throughput: 603 bytes (603)/s, 118 lines parsed/s, 78 published records/s.
```

(2) should it really exclude rows by default though? Pandas `to_numeric` method has 3 options to handle parsing errors, none of which offer to exclude the row: https://pandas.pydata.org/pandas-docs/version/0.22.0/generated/pandas.to_numeric.html (it's a convert function not a loading function though)

```
errors : {‘ignore’, ‘raise’, ‘coerce’}, default ‘raise’

If ‘raise’, then invalid parsing will raise an exception
If ‘coerce’, then invalid parsing will be set as NaN
If ‘ignore’, then invalid parsing will return the input
```

`raise` is probably the best default while `coerce` is the one I would expect in the case described above.

**Comment by rcolle** [comment]
Duplicated #58 
Related to https://github.com/activeviam/atoti/issues/266

**Comment by fabiencelier** [comment]
Hello,
In next release a warning will be issued in the notebook when a loading error occur.
A more complete report about the store loading will be available in store.loading_report
