### ISSUE TITLE
ClassCastException: Incorrect type double[]

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#737]
## Steps to reproduce

In my environment, I have the plugin `atoti-directquery-bigquery` installed.

I was able to successfully create a table with `read_csv` for the dataset _IRDelta.csv:

```
irDeltaTbl = session.read_csv(
    "data/_IRDelta.csv",
    table_name="IR Delta",
    keys=["AsOfDate", "TradeID", "RiskFactor", "RiskFactorType", "RiskMeasure"],
    array_separator=";",
)
```

However, with another dataset - sensitivities_4.csv, I was able to create the table but no data loaded:
```
sensitivities_tbl = session.read_csv(
    "data/sensitivities_4.csv",
    table_name="Sensitivities",
    keys=["TradeId", "AsOfDate", "BookId"],
    array_separator=";",
)
```

The following exception was thrown in the log:
```
java.lang.ClassCastException: Incorrect type double[] for tuple with value [D@70eefc4a for lookup in dictionary of type NullableDictionary. Exception in store: Sensitivities, field: PnlVector, for tuple: [2019404784, 07/10/2019, 1426, 610.28, 10.09, 58.73, 61.03, -2.29, 3893.77, -25.95, 32.0, -229.88, [D@70eefc4a].
	at com.qfs.store.transaction.impl.TransactionManager.transformToFullRecords(TransactionManager.java:1464) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.store.transaction.impl.TransactionManager.addAll(TransactionManager.java:1312) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.store.transaction.ITransactionalWriter.addAll(ITransactionalWriter.java:56) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.store.transaction.impl.AlterableTransactionManager.addAll(AlterableTransactionManager.java:287) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.source.impl.TuplePublisher.publish(TuplePublisher.java:115) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.source.impl.StoreMessage.append(StoreMessage.java:115) ~[atoti-directquery-bigquery.jar:na]
	at com.qfs.msg.csv.impl.Parser.parse(Parser.java:236) ~[atoti-aws.jar:na]
	at com.qfs.msg.csv.impl.ParserTask.parseIteration(ParserTask.java:404) ~[atoti-aws.jar:na]
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:255) ~[atoti-aws.jar:na]
	at com.qfs.msg.csv.impl.ParserTask.call(ParserTask.java:46) ~[atoti-aws.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	at com.qfs.msg.csv.impl.ParserThread.run(ParserThread.java:57) ~[atoti-aws.jar:na]
	Suppressed: java.lang.ClassCastException: null
```

[sensitivities_4.csv](https://github.com/atoti/atoti/files/10545391/sensitivities_4.csv)
[_IRDelta.csv](https://github.com/atoti/atoti/files/10545394/_IRDelta.csv)
[server.log](https://github.com/atoti/atoti/files/10545397/server.log)

## Environment

- atoti: 0.7.2
- Python: 3.10.0
- Operating system: win32

**Comment by rcolle** [comment]
Do you have the same issue when the `atoti-directquery-bigquery` plugin is not installed?

**Comment by HuifangYeo** [comment]
Hi @rcolle,

I discovered that this problem only happens after I delete the table and re-execute the cell within the same session.
Please see the GIF below:

![del_tables](https://user-images.githubusercontent.com/35210495/215923440-34a233f4-c1ab-4cf5-810e-be6a38632894.gif)

[training.zip](https://github.com/atoti/atoti/files/10552415/training.zip)
