### ISSUE TITLE
Extra columns in pandas dataframe not supported

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#758]
## Steps to reproduce

The notebook was working previously on 0.7.2. 
```py
rt_chunks_df = pd.read_csv(
    "https://data.atoti.io/notebooks/intraday-liquidity/cashflow_realtime_20211015.csv",
    chunksize=500,
    parse_dates=["Transaction_Date", "Settlement_Date"],
)

for chunk in rt_chunks_df:
    t = chunk.reset_index()
    payment_tbl.load_pandas(t)
    time.sleep(1)
print("End")
```

The above code threw out the below exception when trying to load the data with `payment_tbl.load_pandas(t)`:
```
AtotiJavaException: class org.apache.arrow.vector.util.Text cannot be cast to class java.lang.String (org.apache.arrow.vector.util.Text is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @3532ec19; java.lang.String is in module java.base of loader 'bootstrap')
```

I have tried to read the data directly into a pandas dataframe instead of chunks and I have been able to load the data successfully without issue.

[main.zip](https://github.com/atoti/atoti/files/10809672/main.zip)

## Environment

- atoti: 0.7.3
- Python: 3.9.13
- Operating system: win32

## Logs (if relevant)

[server.log](https://github.com/atoti/atoti/files/10809658/server.log)

<details><pre>
2023-02-23 09:57:52.311  WARN 38788 --- [Thread-1] i.InstanceMetadataServiceResourceFetcher : Fail to retrieve token 

com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100) ~[atoti-aws.jar:na]
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91) ~[atoti-aws.jar:na]
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69) ~[atoti-aws.jar:na]
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:60) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:48) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:124) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:80) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:166) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75) ~[atoti-aws.jar:na]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117) ~[atoti-aws.jar:na]
	at io.atoti.loading.s3.impl.S3CredentialsProviderChain.getCredentials(S3CredentialsProviderChain.java:29) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:845) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[atoti-aws.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6431) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6404) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5441) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346) ~[atoti-aws.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427) ~[atoti-aws.jar:na]
	at io.atoti.loading.s3.impl.S3Path.exist(S3Path.java:244) ~[atoti-aws.jar:na]
	at io.atoti.loading.impl.AFileBasedDataTable.<init>(AFileBasedDataTable.java:28) ~[patachou-core-6.0.3-20230222-192541-08c2aaa0.jar!/:na]
	at io.atoti.loading.parquet.impl.ParquetDataTable.<init>(ParquetDataTable.java:45) ~[patachou-core-6.0.3-20230222-192541-08c2aaa0.jar!/:na]
	at io.atoti.loading.parquet.impl.ParquetDataTableFactory.createTable(ParquetDataTableFactory.java:31) ~[patachou-core-6.0.3-20230222-192541-08c2aaa0.jar!/:na]
	at io.atoti.loading.parquet.impl.ParquetDataTableFactory.createTable(ParquetDataTableFactory.java:10) ~[patachou-core-6.0.3-20230222-192541-08c2aaa0.jar!/:na]
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.inferTypesFromDataSource(OutsideTransactionDataApiImpl.java:105) ~[patachou-core-6.0.3-20230222-192541-08c2aaa0.jar!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) ~[py4j-0.10.9.jar!/:na]
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) ~[py4j-0.10.9.jar!/:na]
	at py4j.Gateway.invoke(Gateway.java:282) ~[py4j-0.10.9.jar!/:na]
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) ~[py4j-0.10.9.jar!/:na]
	at py4j.commands.CallCommand.execute(CallCommand.java:79) ~[py4j-0.10.9.jar!/:na]
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182) ~[py4j-0.10.9.jar!/:na]
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106) ~[py4j-0.10.9.jar!/:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.SocketException: Network is unreachable: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na]
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:95) ~[atoti-aws.jar:na]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80) ~[atoti-aws.jar:na]
	... 46 common frames omitted
</pre></details>

**Comment by HuifangYeo** [comment]
It turns out that because the pandas DataFrame has extra columns - index, therefore I wasn't able to load the DataFrame into the table. After I select precisely the atot table column from the dataframe, then loading works successfully.

Is this the expected behaviour?

**Comment by tibdex** [comment]
I can reproduce.

In 0.7.2 this works:

```py
import pandas as pd
import atoti as tt

session = tt.Session()

table = session.read_pandas(
    pd.DataFrame({"int": [1], "string": ["A"]}),
    table_name="Default",
)
table.load_pandas(pd.DataFrame({"float": [1.5], "int": [2], "string": ["B"]}))
```

but in 0.7.3 it fails with:

```
atoti._exceptions.AtotiJavaException: An error occurred while calling o42.loadDataSourceIntoStore.
E           : java.lang.IndexOutOfBoundsException: Index: 2 Size: 2
E           	at java.base/java.util.ImmutableCollections$AbstractImmutableList.outOfBounds(Unknown Source)
E           	at java.base/java.util.ImmutableCollections$List12.get(Unknown Source)
E           	at io.atoti.loading.arrow.ArrowParser.parseColumn(ArrowParser.java:75)
E           	at io.atoti.loading.arrow.ArrowParser.parse(ArrowParser.java:64)
E           	at io.atoti.loading.arrow.ArrowDataTable.loadWithinTransaction(ArrowDataTable.java:51)
E           	at io.atoti.loading.impl.DataTableOperationUnit.executeOperation(DataTableOperationUnit.java:18)
E           	at io.atoti.api.impl.DataApiImpl.executeOperation(DataApiImpl.java:100)
E           	at io.atoti.api.impl.DataApiImpl.loadDataSourceIntoStore(DataApiImpl.java:121)
E           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
E           	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
E           	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
E           	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E           	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E           	at py4j.Gateway.invoke(Gateway.java:282)
E           	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E           	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E           	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
E           	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
E           	at java.base/java.lang.Thread.run(Unknown Source)
```

When the extra column is at the end:

```diff
- table.load_pandas(pd.DataFrame({"float": [1.5], "int": [2], "string": ["B"]}))
+ table.load_pandas(pd.DataFrame({"int": [2], "string": ["B"], "float": [1.5]}))
```

it works in 0.7.3 too.

---

In your specific case, a fix is to do:

```diff
  for chunk in rt_chunks_df:
-    t = chunk.reset_index()
     payment_tbl.load_pandas(t)
```

since `chunk` does not have an index to begin with.
