### ISSUE TITLE
Atoti 0.8.2 and Python 3.9.1

### ISSUE THREAD

**Issue by conorpbrennan** [atoti/atoti#793]
## Steps to reproduce

using Python 3.9.1
`import atoti as tt` fails

## Actual Result

```
(base) C:\Users\cbrennan\Workspace>python
Python 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:50:22) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import atoti as tt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Continuum\miniconda3\lib\site-packages\atoti\__init__.py", line 5, in <module>
    from atoti_core import BaseSession
  File "C:\ProgramData\Continuum\miniconda3\lib\site-packages\atoti_core\__init__.py", line 3, in <module>
    from .activeviam_client import *
  File "C:\ProgramData\Continuum\miniconda3\lib\site-packages\atoti_core\activeviam_client.py", line 37, in <module>
    from .fetch_json import JSON_CONTENT_TYPE, JsonResponse, fetch_json
  File "C:\ProgramData\Continuum\miniconda3\lib\site-packages\atoti_core\fetch_json.py", line 40, in <module>
    json_dump_default: Optional[_JsonDumpDefault] = ...,
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 262, in inner
    return func(*args, **kwds)
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 463, in Optional
    return Union[arg, type(None)]
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 262, in inner
    return func(*args, **kwds)
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "C:\ProgramData\Continuum\miniconda3\lib\typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
```

## Environment

- atoti:
- Python:
- Operating System:

**Comment by conorpbrennan** [comment]
Atoti 0.8.2
Python 3.9.1
Import atoti as tt

Fails
It seems to me that Atoti 0.8.x is not supported on Python 3.9.1
Your change log says support for Python 3.8 was removed after Atoti 0.8.0
Can you import Atoti 0.8.02 successfully on Python 3.9.1?

**Comment by tibdex** [comment]
This is a bug in Python 3.9.1 itself: https://bugs.python.org/issue42965. You can upgrade to a more recent 3.9 release to fix the problem. For instance, [the project template uses 3.9.17](https://github.com/atoti/project-template/actions/runs/5545995505/jobs/10125691580#step:3:49).
