### ISSUE TITLE
An error occurred while calling o143.generateSchemaGraph.

### ISSUE THREAD

**Issue by TravisWhip** [atoti/atoti#822]
## Steps to reproduce

Print any schema, for instance:

`session.tables.schema`
`session.cube.schema`

## Actual Result

```
An error occurred while calling o42.generateSchemaGraph.
: guru.nidi.graphviz.engine.GraphvizException: None of the provided engines could be initialized.
	at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:162)
	at guru.nidi.graphviz.engine.Graphviz.doExecute(Graphviz.java:312)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:292)
	at guru.nidi.graphviz.engine.Renderer.execute(Renderer.java:139)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:59)
	at com.activeviam.graphviz.DataStoreGraphBuilder.writeGraph(DataStoreGraphBuilder.java:110)
	at com.activeviam.graphviz.DataStoreGraphBuilder.buildDatastoreSchema(DataStoreGraphBuilder.java:105)
	at io.atoti.api.impl.OutsideTransactionDataApiImpl.generateSchemaGraph(OutsideTransactionDataApiImpl.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
```

## Expected Result

A graphical representation of the schema as noted in the Join section of the Tutorial (Cell #22): https://docs.atoti.io/latest/getting_started/tutorial/tutorial.html#Join

## Environment

Windows: 11
Python: 3.12.1
Jupyter-lab: 4.0.12
atoti: 0.8.8
atoti-core: 0.8.8
atoti-jupyterlab: 0.8.8
atoti-query: 0.8.8

## Related Issues:
The only related issue I can find is this: https://github.com/atoti/atoti/issues/567, which is said to have been fixed.

**Comment by TravisWhip** [comment]
It should be noted that I just installed everything today, Python Atoti and JupyterLab so I should be as up to date as possible.

**Comment by tibdex** [comment]
See [this](https://docs.atoti.io/0.8.8/api/atoti.tables.Tables.schema.html#atoti.tables.Tables.schema). You either need to update to JupyterLab 4.1.0-rc or to [install graphviz](https://graphviz.org/download/).

**Comment by TravisWhip** [comment]
Following the default installation for Graphviz 9.0 did not seem to work. 

However, installing JupyterLab 4.1.0-rc did work.

I was able to install JupyterLab 4.1.0-rc with: 
`pip install jupyterlab==4.1.0-rc`

Thanks.
