### ISSUE TITLE
FileNotFound error during copy tutorial

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#90]
## Steps to reproduce

Reported by a user after installing atoti with `pip` without following the requirements step (not sure there is a link but mentioning it just in case).

## Actual Result

Sorry for the low resolution picture: 
![screenshot-drive google com-2020 06 29-16_06_37](https://user-images.githubusercontent.com/4415696/86016500-21af9c00-ba23-11ea-944e-2368f250c70a.png)

```console
> python -m atoti.copy_tutorial tutorial
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Environment

- atoti: 0.4.1
- Python: ?
- Operating System: Windows

**Comment by fabiencelier** [comment]
Probably Java missing, the error occurs while calling `[java_path, "-version"]`

Sadly copying the tutorial triggers these java version and license check

**Comment by rcolle** [comment]
Removing java from my PATH, I get the same error (in English and HiFi):

```
(test) C:\Users\r.colle> python -m atoti.copy_tutorial tutorial
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\test\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\tools\miniconda3\envs\test\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\tools\miniconda3\envs\test\lib\site-packages\atoti\__init__.py", line 38, in <module>
    (_EDITION, _LICENSE_END_DATE) = retrieve_info_from_jar()
  File "C:\tools\miniconda3\envs\test\lib\site-packages\atoti\_java_utils.py", line 31, in retrieve_info_from_jar
    check_java_version(java_path, [11])
  File "C:\tools\miniconda3\envs\test\lib\site-packages\atoti\_compatibility.py", line 37, in check_java_version
    command_result = subprocess.check_output(  # nosec
  File "C:\tools\miniconda3\envs\test\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\tools\miniconda3\envs\test\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\tools\miniconda3\envs\test\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\tools\miniconda3\envs\test\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
