### ISSUE TITLE
Notebooks under ./main/03-use-cases are not running

### ISSUE THREAD

**Issue by agent3133** [atoti/atoti#968]
## Description

Use-Cases Notebooks are not running with Atoti 0.9.* becauses of changes in starting of sessions to "atoti.Session.start()".

Apart from that, there seems to be an issue with ".read_csv().

After executing
'''python3 
instruments = session.read_csv(
    "s3://data.atoti.io/notebooks/var/instruments.csv",
    keys=["instrument_code"],
    table_name="Instruments",
)
''''
i've got an error

'''
Py4JJavaError: An error occurred while calling o8.discoverCsvFileFormat.
: java.nio.file.InvalidPathException: Illegal char <:> at index 2: s3://data.atoti.io/notebooks/var/instruments.csv
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at com.activeviam.tech.core.internal.util.FileSystemUtils.getResourceUrl(FileSystemUtils.java:186)
	at io.atoti.runtime.private_.util.files.LocalPath.file(LocalPath.java:183)
	at io.atoti.runtime.private_.util.files.LocalPath.toAbsolutePath(LocalPath.java:219)
	at io.atoti.runtime.private_.util.files.LocalPath.checkIsAbsolutePath(LocalPath.java:223)
	at io.atoti.runtime.private_.util.files.LocalPath.<init>(LocalPath.java:45)
	at io.atoti.runtime.private_.util.files.FilesUtil.parsePath(FilesUtil.java:83)
	at io.atoti.runtime.private_.loading.csv.impl.CsvDataTableFactory.createTable(CsvDataTableFactory.java:28)
	at io.atoti.runtime.private_.loading.csv.impl.CsvDataTableFactory.createTable(CsvDataTableFactory.java:10)
	at io.atoti.runtime.internal.impl.OutsideTransactionDataApiImpl.discoverCsvFileFormat(OutsideTransactionDataApiImpl.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
'''

**Comment by andrewyang94** [comment]
Hi @agent3133,

Thanks for reaching out to us! To be clear, some of our use case notebooks have not yet been upgraded to the latest version of Atoti Python API. You can see which versions our use case notebooks are using viewing the `Browse by use case` in the README: https://github.com/atoti/atoti/tree/main/03-use-cases#browse-by-use-case.

Now for the `.read_csv()` issue, can you tell me which notebook you're referring to? I can try and reproduce the issue on my side to investigate.

Thanks,
Andrew

**Comment by andrewyang94** [comment]
Hi @agent3133,

I tried to take a look into this for you and I'm figuring that the error that you were seeing was in relation to [https://github.com/atoti/atoti/blob/main/03-use-cases/01-finance/risk-management/market-risk/value-at-risk/main.ipynb](https://github.com/atoti/atoti/blob/main/03-use-cases/01-finance/risk-management/market-risk/value-at-risk/main.ipynb). Now this notebook is one of the notebooks that have not yet been upgraded to the latest Atoti Python API version, so that checks out, but for your `read_csv` issue, I believe this is because you need to install the `atoti-aws` plugin.

To install this plugin, you can do a `pip install 'atoti[aws]'`, but if you haven't already done so, we highly recommend running the following commands at the root of the repository to create a virtual environment already complete with the necessary dependencies to run all of our notebooks:

```
pip install uv
uv sync --python 3.10
uv run jupyter-lab
```

Let me know if this helps!

-Andrew
